# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_gkecluster.yaml

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: Dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: Dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: Optional[str] = None


class Crossplane(BaseModel):
    compositionRef: Optional[CompositionRef] = None
    compositionRevisionRef: Optional[CompositionRevisionRef] = None
    compositionRevisionSelector: Optional[CompositionRevisionSelector] = None
    compositionSelector: Optional[CompositionSelector] = None
    compositionUpdatePolicy: Optional[Literal['Automatic', 'Manual']] = None
    resourceRefs: Optional[List[ResourceRef]] = None


class Networking(BaseModel):
    nodeCidr: Optional[constr(max_length=18)] = '10.0.0.0/24'
    """
    Primary IP range for nodes.
    """
    podCidr: Optional[constr(max_length=18)] = '10.1.0.0/16'
    """
    Secondary IP range for pods.
    """
    serviceCidr: Optional[constr(max_length=18)] = '10.2.0.0/16'
    """
    Secondary IP range for services.
    """


class Gpu(BaseModel):
    acceleratorCount: Optional[conint(ge=1, le=16)] = 1
    """
    Number of GPUs to attach per node.
    """
    acceleratorType: constr(min_length=1, max_length=63)
    """
    GPU accelerator type (e.g. nvidia-tesla-a100, nvidia-h100-80gb, nvidia-l4). Attached to each node along with acceleratorCount.
    """


class Zone(RootModel[constr(min_length=1, max_length=63)]):
    root: constr(min_length=1, max_length=63)


class NodePool(BaseModel):
    diskSizeGb: Optional[conint(ge=10, le=65536)] = 100
    """
    Boot disk size in GB.
    """
    gpu: Optional[Gpu] = None
    """
    GPU configuration. Required when role is GPU.
    """
    machineType: constr(min_length=1, max_length=63)
    """
    GCE machine type (e.g. e2-standard-4, a2-highgpu-8g, g2-standard-48).
    """
    maxNodeCount: Optional[conint(ge=0, le=1000)] = 8
    """
    Maximum number of nodes for autoscaling.
    """
    minNodeCount: Optional[conint(ge=0, le=1000)] = 0
    """
    Minimum number of nodes for autoscaling. Set to 1 or higher for pools that must always be available.
    """
    name: constr(min_length=1, max_length=40)
    """
    Unique name for this node pool. Used as a suffix in the GKE NodePool resource name.
    """
    nodeCount: Optional[conint(ge=0, le=1000)] = 1
    """
    Initial number of nodes.
    """
    role: Literal['System', 'GPU']
    """
    Determines what workloads this pool runs. System pools host controllers, gateways, and infrastructure. GPU pools host inference workloads and are tainted to exclude non-GPU pods.
    """
    zones: Optional[List[Zone]] = Field(None, max_length=8, min_length=1)
    """
    Zones to restrict this node pool to. Required for GPU pools because not all zones in a region have every GPU type. Example: ["us-central1-a", "us-central1-b"].
    """


class Spec(BaseModel):
    crossplane: Optional[Crossplane] = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    kubernetesVersion: Optional[constr(min_length=1, max_length=16)] = '1.35'
    """
    GKE cluster Kubernetes version. Must be a version supported by the REGULAR release channel.
    """
    networking: Optional[Networking] = None
    """
    VPC networking configuration. Defaults are suitable for standalone clusters. Override when VPC-peering multiple clusters to avoid CIDR collisions.
    """
    nodePools: List[NodePool] = Field(..., max_length=8, min_length=1)
    """
    Node pools for the cluster. At least one System pool is required for controllers and infrastructure workloads.
    """
    project: constr(min_length=6, max_length=30)
    """
    GCP project ID where the cluster will be created.
    """
    region: constr(min_length=1, max_length=32)
    """
    GCP region for the cluster (e.g. us-central1, europe-west4).
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    message: Optional[str] = None
    observedGeneration: Optional[int] = None
    reason: str
    status: str
    type: str


class Network(BaseModel):
    name: Optional[str] = None
    """
    Name of the composed VPC network.
    """


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig', 'GCPServiceAccountKey']
    """
    The type of credential this secret contains. Kubeconfig contains a kubeconfig file with the cluster endpoint and CA certificate. GCPServiceAccountKey contains a GCP service account JSON key that can authenticate to the cluster via GKE IAM.
    """


class Status(BaseModel):
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    network: Optional[Network] = None
    """
    The VPC network this cluster runs in. Consumers pin network-scoped resources (e.g. the ModelCache Filestore StorageClass) to this name. Populated once the composed Network is observed; the name carries the provider's generated suffix, so it can't be derived from the XR name.
    """
    secrets: Optional[List[Secret]] = None
    """
    Secrets produced by this cluster. Consumers use these to authenticate to the cluster. All secrets are in the same namespace as this GKECluster.
    """


class GKECluster(BaseModel):
    apiVersion: Optional[Literal['infrastructure.modelplane.ai/v1alpha1']] = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['GKECluster']] = 'GKECluster'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    GKEClusterSpec defines the desired state of GKECluster.
    """
    status: Optional[Status] = None
    """
    GKEClusterStatus defines the observed state of GKECluster.
    """


class GKEClusterList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[GKECluster]
    """
    List of gkeclusters. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """