# generated by datamodel-codegen:
#   filename:  workdir/ec2_aws_upbound_io_v1beta1_securitygroupingressrule.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class PrefixListIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class PrefixListIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ReferencedSecurityGroupIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ReferencedSecurityGroupIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class SecurityGroupIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SecurityGroupIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    cidrIpv4: str | None = None
    """
    The source IPv4 CIDR range.
    """
    cidrIpv6: str | None = None
    """
    The source IPv6 CIDR range.
    """
    description: str | None = None
    """
    The security group rule description.
    """
    fromPort: float | None = None
    """
    The start of port range for the TCP and UDP protocols, or an ICMP/ICMPv6 type.
    """
    ipProtocol: str | None = None
    """
    The IP protocol name or number. Use -1 to specify all protocols. Note that if ip_protocol is set to -1, it translates to all protocols, all port ranges, and from_port and to_port values should not be defined.
    """
    prefixListId: str | None = None
    """
    The ID of the source prefix list.
    """
    prefixListIdRef: PrefixListIdRef | None = None
    """
    Reference to a ManagedPrefixList in ec2 to populate prefixListId.
    """
    prefixListIdSelector: PrefixListIdSelector | None = None
    """
    Selector for a ManagedPrefixList in ec2 to populate prefixListId.
    """
    referencedSecurityGroupId: str | None = None
    """
    The source security group that is referenced in the rule.
    """
    referencedSecurityGroupIdRef: ReferencedSecurityGroupIdRef | None = None
    """
    Reference to a SecurityGroup in ec2 to populate referencedSecurityGroupId.
    """
    referencedSecurityGroupIdSelector: ReferencedSecurityGroupIdSelector | None = None
    """
    Selector for a SecurityGroup in ec2 to populate referencedSecurityGroupId.
    """
    region: str
    """
    Region where this resource will be managed. Defaults to the Region set in the provider configuration.
    Region is the region you'd like your resource to be created in.
    """
    securityGroupId: str | None = None
    """
    The ID of the security group.
    """
    securityGroupIdRef: SecurityGroupIdRef | None = None
    """
    Reference to a SecurityGroup in ec2 to populate securityGroupId.
    """
    securityGroupIdSelector: SecurityGroupIdSelector | None = None
    """
    Selector for a SecurityGroup in ec2 to populate securityGroupId.
    """
    tags: dict[str, str] | None = None
    """
    Key-value map of resource tags.
    """
    toPort: float | None = None
    """
    The end of port range for the TCP and UDP protocols, or an ICMP/ICMPv6 code.
    """


class InitProvider(BaseModel):
    cidrIpv4: str | None = None
    """
    The source IPv4 CIDR range.
    """
    cidrIpv6: str | None = None
    """
    The source IPv6 CIDR range.
    """
    description: str | None = None
    """
    The security group rule description.
    """
    fromPort: float | None = None
    """
    The start of port range for the TCP and UDP protocols, or an ICMP/ICMPv6 type.
    """
    ipProtocol: str | None = None
    """
    The IP protocol name or number. Use -1 to specify all protocols. Note that if ip_protocol is set to -1, it translates to all protocols, all port ranges, and from_port and to_port values should not be defined.
    """
    prefixListId: str | None = None
    """
    The ID of the source prefix list.
    """
    prefixListIdRef: PrefixListIdRef | None = None
    """
    Reference to a ManagedPrefixList in ec2 to populate prefixListId.
    """
    prefixListIdSelector: PrefixListIdSelector | None = None
    """
    Selector for a ManagedPrefixList in ec2 to populate prefixListId.
    """
    referencedSecurityGroupId: str | None = None
    """
    The source security group that is referenced in the rule.
    """
    referencedSecurityGroupIdRef: ReferencedSecurityGroupIdRef | None = None
    """
    Reference to a SecurityGroup in ec2 to populate referencedSecurityGroupId.
    """
    referencedSecurityGroupIdSelector: ReferencedSecurityGroupIdSelector | None = None
    """
    Selector for a SecurityGroup in ec2 to populate referencedSecurityGroupId.
    """
    securityGroupId: str | None = None
    """
    The ID of the security group.
    """
    securityGroupIdRef: SecurityGroupIdRef | None = None
    """
    Reference to a SecurityGroup in ec2 to populate securityGroupId.
    """
    securityGroupIdSelector: SecurityGroupIdSelector | None = None
    """
    Selector for a SecurityGroup in ec2 to populate securityGroupId.
    """
    tags: dict[str, str] | None = None
    """
    Key-value map of resource tags.
    """
    toPort: float | None = None
    """
    The end of port range for the TCP and UDP protocols, or an ICMP/ICMPv6 code.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    arn: str | None = None
    """
    The Amazon Resource Name (ARN) of the security group rule.
    """
    cidrIpv4: str | None = None
    """
    The source IPv4 CIDR range.
    """
    cidrIpv6: str | None = None
    """
    The source IPv6 CIDR range.
    """
    description: str | None = None
    """
    The security group rule description.
    """
    fromPort: float | None = None
    """
    The start of port range for the TCP and UDP protocols, or an ICMP/ICMPv6 type.
    """
    id: str | None = None
    """
    (String) ID of the security group rule.
    """
    ipProtocol: str | None = None
    """
    The IP protocol name or number. Use -1 to specify all protocols. Note that if ip_protocol is set to -1, it translates to all protocols, all port ranges, and from_port and to_port values should not be defined.
    """
    prefixListId: str | None = None
    """
    The ID of the source prefix list.
    """
    referencedSecurityGroupId: str | None = None
    """
    The source security group that is referenced in the rule.
    """
    region: str | None = None
    """
    Region where this resource will be managed. Defaults to the Region set in the provider configuration.
    Region is the region you'd like your resource to be created in.
    """
    securityGroupId: str | None = None
    """
    The ID of the security group.
    """
    securityGroupRuleId: str | None = None
    """
    The ID of the security group rule.
    """
    tags: dict[str, str] | None = None
    """
    Key-value map of resource tags.
    """
    tagsAll: dict[str, str] | None = None
    """
    A map of tags assigned to the resource, including those inherited from the provider default_tags configuration block.
    """
    toPort: float | None = None
    """
    The end of port range for the TCP and UDP protocols, or an ICMP/ICMPv6 code.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class SecurityGroupIngressRule(BaseModel):
    apiVersion: Literal['ec2.aws.upbound.io/v1beta1'] | None = (
        'ec2.aws.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['SecurityGroupIngressRule'] | None = 'SecurityGroupIngressRule'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    SecurityGroupIngressRuleSpec defines the desired state of SecurityGroupIngressRule
    """
    status: Status | None = None
    """
    SecurityGroupIngressRuleStatus defines the observed state of SecurityGroupIngressRule.
    """


class SecurityGroupIngressRuleList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[SecurityGroupIngressRule]
    """
    List of securitygroupingressrules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """