# generated by datamodel-codegen:
#   filename:  workdir/compute_gcp_m_upbound_io_v1beta1_resourcepolicy.yaml

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class DiskConsistencyGroupPolicy(BaseModel):
    enabled: Optional[bool] = None
    """
    Enable disk consistency on the resource policy.
    """


class GroupPlacementPolicy(BaseModel):
    availabilityDomainCount: Optional[float] = None
    """
    The number of availability domains instances will be spread across. If two instances are in different
    availability domain, they will not be put in the same low latency network
    """
    collocation: Optional[str] = None
    """
    Collocation specifies whether to place VMs inside the same availability domain on the same low-latency network.
    Specify COLLOCATED to enable collocation. Can only be specified with vm_count. If compute instances are created
    with a COLLOCATED policy, then exactly vm_count instances must be created at the same time with the resource policy
    attached.
    Possible values are: COLLOCATED.
    """
    gpuTopology: Optional[str] = None
    """
    Specifies the shape of the GPU slice, in slice based GPU families eg. A4X.
    """
    vmCount: Optional[float] = None
    """
    Number of VMs in this placement group. Google does not recommend that you use this field
    unless you use a compact policy and you want your policy to work only if it contains this
    exact number of VMs.
    """


class VmStartSchedule(BaseModel):
    schedule: Optional[str] = None
    """
    Specifies the frequency for the operation, using the unix-cron format.
    """


class VmStopSchedule(BaseModel):
    schedule: Optional[str] = None
    """
    Specifies the frequency for the operation, using the unix-cron format.
    """


class InstanceSchedulePolicy(BaseModel):
    expirationTime: Optional[str] = None
    """
    The expiration time of the schedule. The timestamp is an RFC3339 string.
    """
    startTime: Optional[str] = None
    """
    The start time of the schedule. The timestamp is an RFC3339 string.
    """
    timeZone: Optional[str] = None
    """
    Specifies the time zone to be used in interpreting the schedule. The value of this field must be a time zone name
    from the tz database: http://en.wikipedia.org/wiki/Tz_database.
    """
    vmStartSchedule: Optional[VmStartSchedule] = None
    """
    Specifies the schedule for starting instances.
    Structure is documented below.
    """
    vmStopSchedule: Optional[VmStopSchedule] = None
    """
    Specifies the schedule for stopping instances.
    Structure is documented below.
    """


class RetentionPolicy(BaseModel):
    maxRetentionDays: Optional[float] = None
    """
    Maximum age of the snapshot that is allowed to be kept.
    """
    onSourceDiskDelete: Optional[str] = None
    """
    Specifies the behavior to apply to scheduled snapshots when
    the source disk is deleted.
    Default value is KEEP_AUTO_SNAPSHOTS.
    Possible values are: KEEP_AUTO_SNAPSHOTS, APPLY_RETENTION_POLICY.
    """


class DailySchedule(BaseModel):
    daysInCycle: Optional[float] = None
    """
    Defines a schedule with units measured in days. The value determines how many days pass between the start of each cycle. Days in cycle for snapshot schedule policy must be 1.
    """
    startTime: Optional[str] = None
    """
    Time within the window to start the operations.
    It must be in format "HH:MM", where HH : [00-23] and MM : [00-00] GMT.
    """


class HourlySchedule(BaseModel):
    hoursInCycle: Optional[float] = None
    """
    The number of hours between snapshots.
    """
    startTime: Optional[str] = None
    """
    Time within the window to start the operations.
    It must be in format "HH:MM", where HH : [00-23] and MM : [00-00] GMT.
    """


class DayOfWeek(BaseModel):
    day: Optional[str] = None
    """
    The day of the week to create the snapshot. e.g. MONDAY
    Possible values are: MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY.
    """
    startTime: Optional[str] = None
    """
    Time within the window to start the operations.
    It must be in format "HH:MM", where HH : [00-23] and MM : [00-00] GMT.
    """


class WeeklySchedule(BaseModel):
    dayOfWeeks: Optional[List[DayOfWeek]] = None
    """
    May contain up to seven (one for each day of the week) snapshot times.
    Structure is documented below.
    """


class Schedule(BaseModel):
    dailySchedule: Optional[DailySchedule] = None
    """
    The policy will execute every nth day at the specified time.
    Structure is documented below.
    """
    hourlySchedule: Optional[HourlySchedule] = None
    """
    The policy will execute every nth hour starting at the specified time.
    Structure is documented below.
    """
    weeklySchedule: Optional[WeeklySchedule] = None
    """
    Allows specifying a snapshot time for each day of the week.
    Structure is documented below.
    """


class SnapshotProperties(BaseModel):
    chainName: Optional[str] = None
    """
    Creates the new snapshot in the snapshot chain labeled with the
    specified name. The chain name must be 1-63 characters long and comply
    with RFC1035.
    """
    guestFlush: Optional[bool] = None
    """
    Whether to perform a 'guest aware' snapshot.
    """
    labels: Optional[Dict[str, str]] = None
    """
    A set of key-value pairs.
    """
    storageLocations: Optional[List[str]] = None
    """
    Cloud Storage bucket location to store the auto snapshot
    (regional or multi-regional)
    """


class SnapshotSchedulePolicy(BaseModel):
    retentionPolicy: Optional[RetentionPolicy] = None
    """
    Retention policy applied to snapshots created by this resource policy.
    Structure is documented below.
    """
    schedule: Optional[Schedule] = None
    """
    Contains one of an hourlySchedule, dailySchedule, or weeklySchedule.
    Structure is documented below.
    """
    snapshotProperties: Optional[SnapshotProperties] = None
    """
    Properties with which the snapshots are created, such as labels.
    Structure is documented below.
    """


class WorkloadPolicy(BaseModel):
    acceleratorTopology: Optional[str] = None
    """
    The accelerator topology. This field can be set only when the workload policy type is HIGH_THROUGHPUT
    and cannot be set if max topology distance is set.
    """
    maxTopologyDistance: Optional[str] = None
    """
    The maximum topology distance. This field can be set only when the workload policy type is HIGH_THROUGHPUT
    and cannot be set if accelerator topology is set.
    Possible values are: BLOCK, CLUSTER, SUBBLOCK.
    """
    type: Optional[str] = None
    """
    The type of workload policy.
    Possible values are: HIGH_AVAILABILITY, HIGH_THROUGHPUT.
    """


class ForProvider(BaseModel):
    description: Optional[str] = None
    """
    An optional description of this resource. Provide this property when you create the resource.
    """
    diskConsistencyGroupPolicy: Optional[DiskConsistencyGroupPolicy] = None
    """
    Replication consistency group for asynchronous disk replication.
    Structure is documented below.
    """
    groupPlacementPolicy: Optional[GroupPlacementPolicy] = None
    """
    Resource policy for instances used for placement configuration.
    Structure is documented below.
    """
    instanceSchedulePolicy: Optional[InstanceSchedulePolicy] = None
    """
    Resource policy for scheduling instance operations.
    Structure is documented below.
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    region: str
    """
    Region where resource policy resides.
    """
    snapshotSchedulePolicy: Optional[SnapshotSchedulePolicy] = None
    """
    Policy for creating snapshots of persistent disks.
    Structure is documented below.
    """
    workloadPolicy: Optional[WorkloadPolicy] = None
    """
    Represents the workload policy.
    Structure is documented below.
    """


class InitProvider(BaseModel):
    description: Optional[str] = None
    """
    An optional description of this resource. Provide this property when you create the resource.
    """
    diskConsistencyGroupPolicy: Optional[DiskConsistencyGroupPolicy] = None
    """
    Replication consistency group for asynchronous disk replication.
    Structure is documented below.
    """
    groupPlacementPolicy: Optional[GroupPlacementPolicy] = None
    """
    Resource policy for instances used for placement configuration.
    Structure is documented below.
    """
    instanceSchedulePolicy: Optional[InstanceSchedulePolicy] = None
    """
    Resource policy for scheduling instance operations.
    Structure is documented below.
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    snapshotSchedulePolicy: Optional[SnapshotSchedulePolicy] = None
    """
    Policy for creating snapshots of persistent disks.
    Structure is documented below.
    """
    workloadPolicy: Optional[WorkloadPolicy] = None
    """
    Represents the workload policy.
    Structure is documented below.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: Optional[InitProvider] = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: Optional[
        List[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
    ] = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: Optional[ProviderConfigRef] = Field(
        default_factory=lambda: ProviderConfigRef.model_validate(
            {'kind': 'ClusterProviderConfig', 'name': 'default'}
        )
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: Optional[WriteConnectionSecretToRef] = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    description: Optional[str] = None
    """
    An optional description of this resource. Provide this property when you create the resource.
    """
    diskConsistencyGroupPolicy: Optional[DiskConsistencyGroupPolicy] = None
    """
    Replication consistency group for asynchronous disk replication.
    Structure is documented below.
    """
    groupPlacementPolicy: Optional[GroupPlacementPolicy] = None
    """
    Resource policy for instances used for placement configuration.
    Structure is documented below.
    """
    id: Optional[str] = None
    """
    an identifier for the resource with format projects/{{project}}/regions/{{region}}/resourcePolicies/{{name}}
    """
    instanceSchedulePolicy: Optional[InstanceSchedulePolicy] = None
    """
    Resource policy for scheduling instance operations.
    Structure is documented below.
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    region: Optional[str] = None
    """
    Region where resource policy resides.
    """
    selfLink: Optional[str] = None
    """
    The URI of the created resource.
    """
    snapshotSchedulePolicy: Optional[SnapshotSchedulePolicy] = None
    """
    Policy for creating snapshots of persistent disks.
    Structure is documented below.
    """
    workloadPolicy: Optional[WorkloadPolicy] = None
    """
    Represents the workload policy.
    Structure is documented below.
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: Optional[str] = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: Optional[AtProvider] = None
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class ResourcePolicy(BaseModel):
    apiVersion: Optional[Literal['compute.gcp.m.upbound.io/v1beta1']] = (
        'compute.gcp.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['ResourcePolicy']] = 'ResourcePolicy'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    ResourcePolicySpec defines the desired state of ResourcePolicy
    """
    status: Optional[Status] = None
    """
    ResourcePolicyStatus defines the observed state of ResourcePolicy.
    """


class ResourcePolicyList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[ResourcePolicy]
    """
    List of resourcepolicies. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """