# generated by datamodel-codegen:
#   filename:  workdir/network_azure_m_upbound_io_v1beta1_virtualnetwork.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class DdosProtectionPlan(BaseModel):
    enable: bool | None = None
    """
    Enable/disable DDoS Protection Plan on Virtual Network.
    """
    id: str | None = None
    """
    The ID of DDoS Protection Plan.
    """


class Encryption(BaseModel):
    enforcement: str | None = None
    """
    Specifies if the encrypted Virtual Network allows VM that does not support encryption. Possible values are DropUnencrypted and AllowUnencrypted.
    """


class IpAddressPoolItem(BaseModel):
    id: str | None = None
    """
    The ID of the Network Manager IP Address Management (IPAM) Pool.
    """
    numberOfIpAddresses: str | None = None
    """
    The number of IP addresses to allocated to the Virtual Network. The value must be a string that represents a positive number, e.g., "100".
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ResourceGroupNameRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ResourceGroupNameSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    addressSpace: list[str] | None = None
    """
    The address space that is used the virtual network. You can supply more than one address space.
    """
    bgpCommunity: str | None = None
    """
    The BGP community attribute in format <as-number>:<community-value>.
    """
    ddosProtectionPlan: DdosProtectionPlan | None = None
    """
    A ddos_protection_plan block as documented below.
    """
    edgeZone: str | None = None
    """
    Specifies the Edge Zone within the Azure Region where this Virtual Network should exist. Changing this forces a new Virtual Network to be created.
    """
    encryption: Encryption | None = None
    """
    A encryption block as defined below.
    """
    flowTimeoutInMinutes: float | None = None
    """
    The flow timeout in minutes for the Virtual Network, which is used to enable connection tracking for intra-VM flows. Possible values are between 4 and 30 minutes.
    """
    ipAddressPool: list[IpAddressPoolItem] | None = None
    """
    One or more ip_address_pool blocks as defined below. Only one association of each IP type(IPv4 or IPv6) is allowed.
    """
    location: str | None = None
    """
    The location/region where the virtual network is created. Changing this forces a new resource to be created.
    """
    privateEndpointVnetPolicies: str | None = None
    """
    The Private Endpoint VNet Policies for the Virtual Network. Possible values are Disabled and Basic. Defaults to Disabled.
    """
    resourceGroupName: str | None = None
    """
    The name of the resource group in which to create the virtual network. Changing this forces a new resource to be created.
    """
    resourceGroupNameRef: ResourceGroupNameRef | None = None
    """
    Reference to a ResourceGroup in azure to populate resourceGroupName.
    """
    resourceGroupNameSelector: ResourceGroupNameSelector | None = None
    """
    Selector for a ResourceGroup in azure to populate resourceGroupName.
    """
    tags: dict[str, str] | None = None
    """
    A mapping of tags to assign to the resource.
    """


class InitProvider(BaseModel):
    addressSpace: list[str] | None = None
    """
    The address space that is used the virtual network. You can supply more than one address space.
    """
    bgpCommunity: str | None = None
    """
    The BGP community attribute in format <as-number>:<community-value>.
    """
    ddosProtectionPlan: DdosProtectionPlan | None = None
    """
    A ddos_protection_plan block as documented below.
    """
    edgeZone: str | None = None
    """
    Specifies the Edge Zone within the Azure Region where this Virtual Network should exist. Changing this forces a new Virtual Network to be created.
    """
    encryption: Encryption | None = None
    """
    A encryption block as defined below.
    """
    flowTimeoutInMinutes: float | None = None
    """
    The flow timeout in minutes for the Virtual Network, which is used to enable connection tracking for intra-VM flows. Possible values are between 4 and 30 minutes.
    """
    ipAddressPool: list[IpAddressPoolItem] | None = None
    """
    One or more ip_address_pool blocks as defined below. Only one association of each IP type(IPv4 or IPv6) is allowed.
    """
    location: str | None = None
    """
    The location/region where the virtual network is created. Changing this forces a new resource to be created.
    """
    privateEndpointVnetPolicies: str | None = None
    """
    The Private Endpoint VNet Policies for the Virtual Network. Possible values are Disabled and Basic. Defaults to Disabled.
    """
    tags: dict[str, str] | None = None
    """
    A mapping of tags to assign to the resource.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class IpAddressPoolItemModel(BaseModel):
    allocatedIpAddressPrefixes: list[str] | None = None
    """
    The list of IP address prefixes allocated to the Virtual Network.
    """
    id: str | None = None
    """
    The ID of the Network Manager IP Address Management (IPAM) Pool.
    """
    numberOfIpAddresses: str | None = None
    """
    The number of IP addresses to allocated to the Virtual Network. The value must be a string that represents a positive number, e.g., "100".
    """


class ServiceDelegation(BaseModel):
    actions: list[str] | None = None
    """
    A list of Actions which should be delegated. This list is specific to the service to delegate to. Possible values are Microsoft.Network/networkinterfaces/*, Microsoft.Network/publicIPAddresses/join/action, Microsoft.Network/publicIPAddresses/read, Microsoft.Network/virtualNetworks/read, Microsoft.Network/virtualNetworks/subnets/action, Microsoft.Network/virtualNetworks/subnets/join/action, Microsoft.Network/virtualNetworks/subnets/prepareNetworkPolicies/action, and Microsoft.Network/virtualNetworks/subnets/unprepareNetworkPolicies/action.
    """
    name: str | None = None
    """
    The name of the subnet.
    """


class Delegation(BaseModel):
    name: str | None = None
    """
    The name of the subnet.
    """
    serviceDelegation: ServiceDelegation | None = None
    """
    A service_delegation block as defined below.
    """


class SubnetItem(BaseModel):
    addressPrefixes: list[str] | None = None
    """
    The address prefixes to use for the subnet.
    """
    defaultOutboundAccessEnabled: bool | None = None
    """
    Enable default outbound access to the internet for the subnet. Defaults to true.
    """
    delegation: Delegation | None = None
    """
    One or more delegation blocks as defined below.
    """
    id: str | None = None
    """
    The ID of this subnet.
    """
    name: str | None = None
    """
    The name of the subnet.
    """
    privateEndpointNetworkPolicies: str | None = None
    """
    Enable or Disable network policies for the private endpoint on the subnet. Possible values are Disabled, Enabled, NetworkSecurityGroupEnabled and RouteTableEnabled. Defaults to Disabled.
    """
    privateLinkServiceNetworkPoliciesEnabled: bool | None = None
    """
    Enable or Disable network policies for the private link service on the subnet. Defaults to true.
    """
    routeTableId: str | None = None
    """
    The ID of the Route Table that should be associated with this subnet.
    """
    securityGroup: str | None = None
    """
    The Network Security Group to associate with the subnet. (Referenced by id, i.e. azurerm_network_security_group.example.id)
    """
    serviceEndpointPolicyIds: list[str] | None = None
    """
    The list of IDs of Service Endpoint Policies to associate with the subnet.
    """
    serviceEndpoints: list[str] | None = None
    """
    The list of Service endpoints to associate with the subnet. Possible values include: Microsoft.AzureActiveDirectory, Microsoft.AzureCosmosDB, Microsoft.ContainerRegistry, Microsoft.EventHub, Microsoft.KeyVault, Microsoft.ServiceBus, Microsoft.Sql, Microsoft.Storage, Microsoft.Storage.Global and Microsoft.Web.
    """


class AtProvider(BaseModel):
    addressSpace: list[str] | None = None
    """
    The address space that is used the virtual network. You can supply more than one address space.
    """
    bgpCommunity: str | None = None
    """
    The BGP community attribute in format <as-number>:<community-value>.
    """
    ddosProtectionPlan: DdosProtectionPlan | None = None
    """
    A ddos_protection_plan block as documented below.
    """
    dnsServers: list[str] | None = None
    """
    List of IP addresses of DNS servers
    """
    edgeZone: str | None = None
    """
    Specifies the Edge Zone within the Azure Region where this Virtual Network should exist. Changing this forces a new Virtual Network to be created.
    """
    encryption: Encryption | None = None
    """
    A encryption block as defined below.
    """
    flowTimeoutInMinutes: float | None = None
    """
    The flow timeout in minutes for the Virtual Network, which is used to enable connection tracking for intra-VM flows. Possible values are between 4 and 30 minutes.
    """
    guid: str | None = None
    """
    The GUID of the Virtual Network.
    """
    id: str | None = None
    """
    The Virtual Network ID.
    """
    ipAddressPool: list[IpAddressPoolItemModel] | None = None
    """
    One or more ip_address_pool blocks as defined below. Only one association of each IP type(IPv4 or IPv6) is allowed.
    """
    location: str | None = None
    """
    The location/region where the virtual network is created. Changing this forces a new resource to be created.
    """
    privateEndpointVnetPolicies: str | None = None
    """
    The Private Endpoint VNet Policies for the Virtual Network. Possible values are Disabled and Basic. Defaults to Disabled.
    """
    resourceGroupName: str | None = None
    """
    The name of the resource group in which to create the virtual network. Changing this forces a new resource to be created.
    """
    subnet: list[SubnetItem] | None = None
    """
    Can be specified multiple times to define multiple subnets. Each subnet block supports fields documented below.
    """
    tags: dict[str, str] | None = None
    """
    A mapping of tags to assign to the resource.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class VirtualNetwork(BaseModel):
    apiVersion: Literal['network.azure.m.upbound.io/v1beta1'] | None = (
        'network.azure.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['VirtualNetwork'] | None = 'VirtualNetwork'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    VirtualNetworkSpec defines the desired state of VirtualNetwork
    """
    status: Status | None = None
    """
    VirtualNetworkStatus defines the observed state of VirtualNetwork.
    """


class VirtualNetworkList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[VirtualNetwork]
    """
    List of virtualnetworks. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """