apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dynamobackends.infrastructure.modelplane.ai
spec:
  compositeTypeRef:
    apiVersion: infrastructure.modelplane.ai/v1alpha1
    kind: DynamoBackend
  mode: Pipeline
  pipeline:
  - functionRef:
      name: negzupboundio-modelplane-infracompose-dynamo-backend
    step: compose-dynamo-backend
