# generated by datamodel-codegen:
#   filename:  workdir/compute_gcp_m_upbound_io_v1beta1_regiontargethttpsproxy.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class SslCertificatesRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SslCertificatesSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class UrlMapRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class UrlMapSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    certificateManagerCertificates: list[str] | None = None
    """
    URLs to certificate manager certificate resources that are used to authenticate connections between users and the load balancer.
    sslCertificates and certificateManagerCertificates can't be defined together.
    Accepted format is //certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName} or just the self_link projects/{project}/locations/{location}/certificates/{resourceName}
    """
    description: str | None = None
    """
    An optional description of this resource.
    """
    httpKeepAliveTimeoutSec: float | None = None
    """
    Specifies how long to keep a connection open, after completing a response,
    while there is no matching traffic (in seconds). If an HTTP keepalive is
    not specified, a default value (600 seconds) will be used. For Regioanl
    HTTP(S) load balancer, the minimum allowed value is 5 seconds and the
    maximum allowed value is 600 seconds.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    region: str
    """
    The Region in which the created target https proxy should reside.
    If it is not provided, the provider region is used.
    """
    serverTlsPolicy: str | None = None
    """
    A URL referring to a networksecurity.ServerTlsPolicy
    resource that describes how the proxy should authenticate inbound
    traffic. serverTlsPolicy only applies to a global TargetHttpsProxy
    attached to globalForwardingRules with the loadBalancingScheme
    set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED.
    For details which ServerTlsPolicy resources are accepted with
    INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED
    loadBalancingScheme consult ServerTlsPolicy documentation.
    If left blank, communications are not encrypted.
    If you remove this field from your configuration at the same time as
    deleting or recreating a referenced ServerTlsPolicy resource, you will
    receive a resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy
    within the ServerTlsPolicy resource to avoid this.
    """
    sslCertificates: list[str] | None = None
    """
    URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer.
    At least one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates.
    sslCertificates do not apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
    """
    sslCertificatesRefs: list[SslCertificatesRef] | None = None
    """
    References to RegionSSLCertificate in compute to populate sslCertificates.
    """
    sslCertificatesSelector: SslCertificatesSelector | None = None
    """
    Selector for a list of RegionSSLCertificate in compute to populate sslCertificates.
    """
    sslPolicy: str | None = None
    """
    A reference to the Region SslPolicy resource that will be associated with
    the TargetHttpsProxy resource. If not set, the TargetHttpsProxy
    resource will not have any SSL policy configured.
    """
    urlMap: str | None = None
    """
    A reference to the RegionUrlMap resource that defines the mapping from URL
    to the RegionBackendService.
    """
    urlMapRef: UrlMapRef | None = None
    """
    Reference to a RegionURLMap in compute to populate urlMap.
    """
    urlMapSelector: UrlMapSelector | None = None
    """
    Selector for a RegionURLMap in compute to populate urlMap.
    """


class InitProvider(BaseModel):
    certificateManagerCertificates: list[str] | None = None
    """
    URLs to certificate manager certificate resources that are used to authenticate connections between users and the load balancer.
    sslCertificates and certificateManagerCertificates can't be defined together.
    Accepted format is //certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName} or just the self_link projects/{project}/locations/{location}/certificates/{resourceName}
    """
    description: str | None = None
    """
    An optional description of this resource.
    """
    httpKeepAliveTimeoutSec: float | None = None
    """
    Specifies how long to keep a connection open, after completing a response,
    while there is no matching traffic (in seconds). If an HTTP keepalive is
    not specified, a default value (600 seconds) will be used. For Regioanl
    HTTP(S) load balancer, the minimum allowed value is 5 seconds and the
    maximum allowed value is 600 seconds.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    serverTlsPolicy: str | None = None
    """
    A URL referring to a networksecurity.ServerTlsPolicy
    resource that describes how the proxy should authenticate inbound
    traffic. serverTlsPolicy only applies to a global TargetHttpsProxy
    attached to globalForwardingRules with the loadBalancingScheme
    set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED.
    For details which ServerTlsPolicy resources are accepted with
    INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED
    loadBalancingScheme consult ServerTlsPolicy documentation.
    If left blank, communications are not encrypted.
    If you remove this field from your configuration at the same time as
    deleting or recreating a referenced ServerTlsPolicy resource, you will
    receive a resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy
    within the ServerTlsPolicy resource to avoid this.
    """
    sslCertificates: list[str] | None = None
    """
    URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer.
    At least one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates.
    sslCertificates do not apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
    """
    sslCertificatesRefs: list[SslCertificatesRef] | None = None
    """
    References to RegionSSLCertificate in compute to populate sslCertificates.
    """
    sslCertificatesSelector: SslCertificatesSelector | None = None
    """
    Selector for a list of RegionSSLCertificate in compute to populate sslCertificates.
    """
    sslPolicy: str | None = None
    """
    A reference to the Region SslPolicy resource that will be associated with
    the TargetHttpsProxy resource. If not set, the TargetHttpsProxy
    resource will not have any SSL policy configured.
    """
    urlMap: str | None = None
    """
    A reference to the RegionUrlMap resource that defines the mapping from URL
    to the RegionBackendService.
    """
    urlMapRef: UrlMapRef | None = None
    """
    Reference to a RegionURLMap in compute to populate urlMap.
    """
    urlMapSelector: UrlMapSelector | None = None
    """
    Selector for a RegionURLMap in compute to populate urlMap.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    certificateManagerCertificates: list[str] | None = None
    """
    URLs to certificate manager certificate resources that are used to authenticate connections between users and the load balancer.
    sslCertificates and certificateManagerCertificates can't be defined together.
    Accepted format is //certificatemanager.googleapis.com/projects/{project}/locations/{location}/certificates/{resourceName} or just the self_link projects/{project}/locations/{location}/certificates/{resourceName}
    """
    creationTimestamp: str | None = None
    """
    Creation timestamp in RFC3339 text format.
    """
    description: str | None = None
    """
    An optional description of this resource.
    """
    httpKeepAliveTimeoutSec: float | None = None
    """
    Specifies how long to keep a connection open, after completing a response,
    while there is no matching traffic (in seconds). If an HTTP keepalive is
    not specified, a default value (600 seconds) will be used. For Regioanl
    HTTP(S) load balancer, the minimum allowed value is 5 seconds and the
    maximum allowed value is 600 seconds.
    """
    id: str | None = None
    """
    an identifier for the resource with format projects/{{project}}/regions/{{region}}/targetHttpsProxies/{{name}}
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    proxyId: float | None = None
    """
    The unique identifier for the resource.
    """
    region: str | None = None
    """
    The Region in which the created target https proxy should reside.
    If it is not provided, the provider region is used.
    """
    selfLink: str | None = None
    """
    The URI of the created resource.
    """
    serverTlsPolicy: str | None = None
    """
    A URL referring to a networksecurity.ServerTlsPolicy
    resource that describes how the proxy should authenticate inbound
    traffic. serverTlsPolicy only applies to a global TargetHttpsProxy
    attached to globalForwardingRules with the loadBalancingScheme
    set to INTERNAL_SELF_MANAGED or EXTERNAL or EXTERNAL_MANAGED.
    For details which ServerTlsPolicy resources are accepted with
    INTERNAL_SELF_MANAGED and which with EXTERNAL, EXTERNAL_MANAGED
    loadBalancingScheme consult ServerTlsPolicy documentation.
    If left blank, communications are not encrypted.
    If you remove this field from your configuration at the same time as
    deleting or recreating a referenced ServerTlsPolicy resource, you will
    receive a resourceInUseByAnotherResource error. Use lifecycle.create_before_destroy
    within the ServerTlsPolicy resource to avoid this.
    """
    sslCertificates: list[str] | None = None
    """
    URLs to SslCertificate resources that are used to authenticate connections between users and the load balancer.
    At least one SSL certificate must be specified. Currently, you may specify up to 15 SSL certificates.
    sslCertificates do not apply when the load balancing scheme is set to INTERNAL_SELF_MANAGED.
    """
    sslPolicy: str | None = None
    """
    A reference to the Region SslPolicy resource that will be associated with
    the TargetHttpsProxy resource. If not set, the TargetHttpsProxy
    resource will not have any SSL policy configured.
    """
    urlMap: str | None = None
    """
    A reference to the RegionUrlMap resource that defines the mapping from URL
    to the RegionBackendService.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class RegionTargetHTTPSProxy(BaseModel):
    apiVersion: Literal['compute.gcp.m.upbound.io/v1beta1'] | None = (
        'compute.gcp.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['RegionTargetHTTPSProxy'] | None = 'RegionTargetHTTPSProxy'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    RegionTargetHTTPSProxySpec defines the desired state of RegionTargetHTTPSProxy
    """
    status: Status | None = None
    """
    RegionTargetHTTPSProxyStatus defines the observed state of RegionTargetHTTPSProxy.
    """


class RegionTargetHTTPSProxyList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[RegionTargetHTTPSProxy]
    """
    List of regiontargethttpsproxies. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """