from .model.io.upbound.dev.meta.compositiontest import v1alpha1 as compositiontest
from .model.io.k8s.apimachinery.pkg.apis.meta import v1 as k8s
from .model.ai.modelplane.infrastructure.gkecluster import v1alpha1 as gkeclusterv1alpha1
from .model.io.upbound.gcp.compute.network import v1beta1 as networkv1beta1
from .model.io.upbound.gcp.compute.subnetwork import v1beta2 as subnetv1beta2
from .model.io.upbound.gcp.container.cluster import v1beta2 as clusterv1beta2
from .model.io.upbound.gcp.container.nodepool import v1beta2 as nodepoolv1beta2
from .model.io.upbound.gcp.cloudplatform.serviceaccount import v1beta1 as sav1beta1
from .model.io.upbound.gcp.cloudplatform.serviceaccountkey import v1beta1 as sakeyv1beta1

test = compositiontest.CompositionTest(
    metadata=k8s.ObjectMeta(
        name="gkecluster-basic",
    ),
    spec=compositiontest.Spec(
        compositionPath="apis/gkeclusters/composition.yaml",
        xrPath="examples/gkecluster/example.yaml",
        xrdPath="apis/gkeclusters/definition.yaml",
        timeoutSeconds=120,
        validate=False,
        assertResources=[
            gkeclusterv1alpha1.GKECluster(
                apiVersion="infrastructure.modelplane.ai/v1alpha1",
                kind="GKECluster",
                metadata=k8s.ObjectMeta(
                    name="gpu-us-central1",
                    namespace="gpu-us-central1",
                ),
                spec=gkeclusterv1alpha1.Spec(
                    project="acme-ml-platform",
                    region="us-central1",
                    nodePools=[
                        gkeclusterv1alpha1.NodePool(
                            name="system",
                            role="System",
                            machineType="e2-standard-4",
                            diskSizeGb=100,
                            nodeCount=2,
                            minNodeCount=1,
                            maxNodeCount=4,
                        ),
                        gkeclusterv1alpha1.NodePool(
                            name="gpu-l4",
                            role="GPU",
                            machineType="g2-standard-4",
                            diskSizeGb=100,
                            nodeCount=1,
                            minNodeCount=0,
                            maxNodeCount=2,
                            gpu=gkeclusterv1alpha1.Gpu(
                                acceleratorType="nvidia-l4",
                                acceleratorCount=1,
                            ),
                            zones=["us-central1-a", "us-central1-c"],
                        ),
                    ],
                ),
                status=gkeclusterv1alpha1.Status(
                    secrets=[
                        gkeclusterv1alpha1.Secret(
                            type="Kubeconfig",
                            name="gpu-us-central1-kubeconfig",
                            key="kubeconfig",
                        ),
                        gkeclusterv1alpha1.Secret(
                            type="GCPServiceAccountKey",
                            name="gpu-us-central1-sa-key",
                            key="private_key",
                        ),
                    ],
                ),
            ).model_dump(exclude_unset=True),
            networkv1beta1.Network(
                apiVersion="compute.gcp.upbound.io/v1beta1",
                kind="Network",
                metadata=k8s.ObjectMeta(
                    annotations={
                        "crossplane.io/composition-resource-name": "network",
                    },
                ),
                spec=networkv1beta1.Spec(
                    forProvider=networkv1beta1.ForProvider(
                        project="acme-ml-platform",
                        autoCreateSubnetworks=False,
                    ),
                ),
            ).model_dump(exclude_unset=True),
            clusterv1beta2.Cluster(
                apiVersion="container.gcp.upbound.io/v1beta2",
                kind="Cluster",
                metadata=k8s.ObjectMeta(
                    annotations={
                        "crossplane.io/composition-resource-name": "cluster",
                    },
                ),
                spec=clusterv1beta2.Spec(
                    forProvider=clusterv1beta2.ForProvider(
                        location="us-central1",
                        project="acme-ml-platform",
                        deletionProtection=False,
                        removeDefaultNodePool=True,
                        initialNodeCount=1,
                        minMasterVersion="1.35",
                        networkSelector=clusterv1beta2.NetworkSelector(
                            matchControllerRef=True,
                        ),
                        subnetworkSelector=clusterv1beta2.SubnetworkSelector(
                            matchControllerRef=True,
                        ),
                        ipAllocationPolicy=clusterv1beta2.IpAllocationPolicy(
                            clusterSecondaryRangeName="pods",
                            servicesSecondaryRangeName="services",
                        ),
                        releaseChannel=clusterv1beta2.ReleaseChannel(
                            channel="REGULAR",
                        ),
                        workloadIdentityConfig=clusterv1beta2.WorkloadIdentityConfig(
                            workloadPool="acme-ml-platform.svc.id.goog",
                        ),
                    ),
                    writeConnectionSecretToRef=clusterv1beta2.WriteConnectionSecretToRef(
                        name="gpu-us-central1-kubeconfig",
                        namespace="gpu-us-central1",
                    ),
                ),
            ).model_dump(exclude_unset=True),
            nodepoolv1beta2.NodePool(
                apiVersion="container.gcp.upbound.io/v1beta2",
                kind="NodePool",
                metadata=k8s.ObjectMeta(
                    annotations={
                        "crossplane.io/composition-resource-name": "nodepool-system",
                    },
                ),
                spec=nodepoolv1beta2.Spec(
                    forProvider=nodepoolv1beta2.ForProvider(
                        location="us-central1",
                        project="acme-ml-platform",
                        clusterSelector=nodepoolv1beta2.ClusterSelector(
                            matchControllerRef=True,
                        ),
                        initialNodeCount=2,
                        autoscaling=nodepoolv1beta2.Autoscaling(
                            minNodeCount=1,
                            maxNodeCount=4,
                        ),
                        nodeConfig=nodepoolv1beta2.NodeConfig(
                            machineType="e2-standard-4",
                            diskSizeGb=100,
                            imageType="COS_CONTAINERD",
                            oauthScopes=[
                                "https://www.googleapis.com/auth/cloud-platform",
                            ],
                            labels={
                                "modelplane.ai/pool": "system",
                            },
                        ),
                    ),
                ),
            ).model_dump(exclude_unset=True),
            nodepoolv1beta2.NodePool(
                apiVersion="container.gcp.upbound.io/v1beta2",
                kind="NodePool",
                metadata=k8s.ObjectMeta(
                    annotations={
                        "crossplane.io/composition-resource-name": "nodepool-gpu-l4",
                    },
                ),
                spec=nodepoolv1beta2.Spec(
                    forProvider=nodepoolv1beta2.ForProvider(
                        location="us-central1",
                        project="acme-ml-platform",
                        clusterSelector=nodepoolv1beta2.ClusterSelector(
                            matchControllerRef=True,
                        ),
                        initialNodeCount=1,
                        autoscaling=nodepoolv1beta2.Autoscaling(
                            minNodeCount=0,
                            maxNodeCount=2,
                        ),
                        nodeLocations=["us-central1-a", "us-central1-c"],
                        nodeConfig=nodepoolv1beta2.NodeConfig(
                            machineType="g2-standard-4",
                            diskSizeGb=100,
                            imageType="COS_CONTAINERD",
                            oauthScopes=[
                                "https://www.googleapis.com/auth/cloud-platform",
                            ],
                            labels={
                                "modelplane.ai/gpu": "nvidia-l4",
                                "modelplane.ai/pool": "gpu-l4",
                            },
                            guestAccelerator=[
                                nodepoolv1beta2.GuestAcceleratorItem(
                                    type="nvidia-l4",
                                    count=1,
                                    gpuDriverInstallationConfig=nodepoolv1beta2.GpuDriverInstallationConfig(
                                        gpuDriverVersion="DEFAULT",
                                    ),
                                ),
                            ],
                        ),
                    ),
                ),
            ).model_dump(exclude_unset=True),
            sav1beta1.ServiceAccount(
                apiVersion="cloudplatform.gcp.upbound.io/v1beta1",
                kind="ServiceAccount",
                metadata=k8s.ObjectMeta(
                    annotations={
                        "crossplane.io/composition-resource-name": "service-account",
                    },
                ),
                spec=sav1beta1.Spec(
                    forProvider=sav1beta1.ForProvider(
                        project="acme-ml-platform",
                        displayName="Crossplane GKECluster gpu-us-central1",
                    ),
                ),
            ).model_dump(exclude_unset=True),
            sakeyv1beta1.ServiceAccountKey(
                apiVersion="cloudplatform.gcp.upbound.io/v1beta1",
                kind="ServiceAccountKey",
                metadata=k8s.ObjectMeta(
                    annotations={
                        "crossplane.io/composition-resource-name": "service-account-key",
                    },
                ),
                spec=sakeyv1beta1.Spec(
                    forProvider=sakeyv1beta1.ForProvider(
                        serviceAccountIdSelector=sakeyv1beta1.ServiceAccountIdSelector(
                            matchControllerRef=True,
                        ),
                    ),
                    writeConnectionSecretToRef=sakeyv1beta1.WriteConnectionSecretToRef(
                        name="gpu-us-central1-sa-key",
                        namespace="gpu-us-central1",
                    ),
                ),
            ).model_dump(exclude_unset=True),
        ],
    ),
)
