# generated by datamodel-codegen:
#   filename:  workdir/ops_crossplane_io_v1alpha1_watchoperation.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class SecretRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Credential(BaseModel):
    name: str
    """
    Name of this set of credentials.
    """
    secretRef: SecretRef | None = None
    """
    A SecretRef is a reference to a secret containing credentials that should
    be supplied to the function.
    """
    source: Literal['None', 'Secret']
    """
    Source of the function credentials.
    """


class FunctionRef(BaseModel):
    name: str
    """
    Name of the referenced function.
    """


class RequiredResource(BaseModel):
    apiVersion: str
    """
    APIVersion of resources to select.
    """
    kind: str
    """
    Kind of resources to select.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels matches resources by label selector. Only one of Name or
    MatchLabels may be specified.
    """
    name: str | None = None
    """
    Name matches a single resource by name. Only one of Name or
    MatchLabels may be specified.
    """
    namespace: str | None = None
    """
    Namespace to search for resources. Optional for cluster-scoped resources.
    """
    requirementName: str
    """
    RequirementName uniquely identifies this group of resources.
    This name will be used as the key in RunFunctionRequest.required_resources.
    """


class RequiredSchema(BaseModel):
    apiVersion: str
    """
    APIVersion of the resource kind whose schema is required, e.g. "example.org/v1".
    """
    kind: str
    """
    Kind of resource whose schema is required, e.g. "MyResource".
    """
    requirementName: str
    """
    RequirementName uniquely identifies this schema.
    This name will be used as the key in RunFunctionRequest.required_schemas.
    """


class Requirements(BaseModel):
    requiredResources: list[RequiredResource] | None = None
    """
    RequiredResources that will be fetched before this pipeline step
    is called for the first time.
    """
    requiredSchemas: list[RequiredSchema] | None = None
    """
    RequiredSchemas that will be fetched before this pipeline step
    is called for the first time.
    """


class PipelineItem(BaseModel):
    credentials: list[Credential] | None = None
    """
    Credentials are optional credentials that the operation function needs.
    """
    functionRef: FunctionRef
    """
    FunctionRef is a reference to the function this step should
    execute.
    """
    input: dict[str, Any] | None = None
    """
    Input is an optional, arbitrary Kubernetes resource (i.e. a resource
    with an apiVersion and kind) that will be passed to the unction as
    the 'input' of its RunFunctionRequest.
    """
    requirements: Requirements | None = None
    """
    Requirements are resource requirements that will be satisfied before
    this pipeline step is called for the first time. This allows
    pre-populating required resources without requiring a function to
    request them first.
    """
    step: str
    """
    Step name. Must be unique within its Pipeline.
    """


class Spec(BaseModel):
    mode: Literal['Pipeline'] = 'Pipeline'
    """
    Mode controls what type or "mode" of operation will be used.

    "Pipeline" indicates that an Operation specifies a pipeline of
    functions, each of which is responsible for implementing its logic.
    """
    pipeline: list[PipelineItem] = Field(..., max_length=99, min_length=1)
    """
    Pipeline is a list of operation function steps that will be used when
    this operation runs.
    """
    retryLimit: int | None = None
    """
    RetryLimit configures how many times the operation may fail. When the
    failure limit is exceeded, the operation will not be retried.
    """


class OperationTemplate(BaseModel):
    metadata: dict[str, Any] | None = None
    """
    Standard object metadata.
    """
    spec: Spec
    """
    Spec is the specification of the Operation to be created.
    """


class Watch(BaseModel):
    apiVersion: str
    """
    APIVersion of the resource to watch.
    """
    kind: str
    """
    Kind of the resource to watch.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels selects resources by label. If empty, all resources of the
    specified kind are watched.
    """
    namespace: str | None = None
    """
    Namespace selects resources in a specific namespace. If empty, all
    namespaces are watched. Only applicable for namespaced resources.
    """


class SpecModel(BaseModel):
    concurrencyPolicy: Literal['Allow', 'Forbid', 'Replace'] | None = 'Allow'
    """
    ConcurrencyPolicy specifies how to treat concurrent executions of an
    operation.
    """
    failedHistoryLimit: int | None = 1
    """
    FailedHistoryLimit is the number of failed Operations to retain.
    """
    operationTemplate: OperationTemplate
    """
    OperationTemplate is the template for the Operation to be created.
    """
    successfulHistoryLimit: int | None = 3
    """
    SuccessfulHistoryLimit is the number of successful Operations to retain.
    """
    watch: Watch
    """
    Watch specifies the resource to watch.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class RunningOperationRef(BaseModel):
    name: str
    """
    Name of the active operation.
    """


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastScheduleTime: AwareDatetime | None = None
    """
    LastScheduleTime is the last time the WatchOperation created an
    Operation.
    """
    lastSuccessfulTime: AwareDatetime | None = None
    """
    LastSuccessfulTime is the last time the WatchOperation successfully
    completed an Operation.
    """
    runningOperationRefs: list[RunningOperationRef] | None = None
    """
    RunningOperationRefs is a list of currently running Operations.
    """
    watchingResources: int | None = None
    """
    WatchingResources is the number of resources this WatchOperation is
    currently watching.
    """


class WatchOperation(BaseModel):
    apiVersion: Literal['ops.crossplane.io/v1alpha1'] | None = (
        'ops.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['WatchOperation'] | None = 'WatchOperation'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: SpecModel | None = None
    """
    WatchOperationSpec specifies the desired state of a WatchOperation.
    """
    status: Status | None = None
    """
    WatchOperationStatus represents the observed state of a WatchOperation.
    """


class WatchOperationList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[WatchOperation]
    """
    List of watchoperations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """