# generated by datamodel-codegen:
#   filename:  workdir/compute_gcp_upbound_io_v1beta1_nodetemplate.yaml

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Accelerator(BaseModel):
    acceleratorCount: Optional[float] = None
    """
    The number of the guest accelerator cards exposed to this
    node template.
    """
    acceleratorType: Optional[str] = None
    """
    Full or partial URL of the accelerator type resource to expose
    to this node template.
    """


class Disk(BaseModel):
    diskCount: Optional[float] = None
    """
    Specifies the number of such disks.
    """
    diskSizeGb: Optional[float] = None
    """
    Specifies the size of the disk in base-2 GB.
    """
    diskType: Optional[str] = None
    """
    Specifies the desired disk type on the node. This disk type must be a local storage type (e.g.: local-ssd). Note that for nodeTemplates, this should be the name of the disk type and not its URL.
    """


class NodeTypeFlexibilityItem(BaseModel):
    cpus: Optional[str] = None
    """
    Number of virtual CPUs to use.
    """
    memory: Optional[str] = None
    """
    Physical memory available to the node, defined in MB.
    """


class ServerBindingItem(BaseModel):
    type: Optional[str] = None
    """
    Type of server binding policy. If RESTART_NODE_ON_ANY_SERVER,
    nodes using this template will restart on any physical server
    following a maintenance event.
    If RESTART_NODE_ON_MINIMAL_SERVER, nodes using this template
    will restart on the same physical server following a maintenance
    event, instead of being live migrated to or restarted on a new
    physical server. This option may be useful if you are using
    software licenses tied to the underlying server characteristics
    such as physical sockets or cores, to avoid the need for
    additional licenses when maintenance occurs. However, VMs on such
    nodes will experience outages while maintenance is applied.
    Possible values are: RESTART_NODE_ON_ANY_SERVER, RESTART_NODE_ON_MINIMAL_SERVERS.
    """


class ForProvider(BaseModel):
    accelerators: Optional[List[Accelerator]] = None
    """
    List of the type and count of accelerator cards attached to the
    node template
    Structure is documented below.
    """
    cpuOvercommitType: Optional[str] = None
    """
    CPU overcommit.
    Default value is NONE.
    Possible values are: ENABLED, NONE.
    """
    description: Optional[str] = None
    """
    An optional textual description of the resource.
    """
    disks: Optional[List[Disk]] = None
    """
    List of the type, size and count of disks attached to the
    node template
    Structure is documented below.
    """
    nodeAffinityLabels: Optional[Dict[str, str]] = None
    """
    Labels to use for node affinity, which will be used in
    instance scheduling.
    """
    nodeType: Optional[str] = None
    """
    Node type to use for nodes group that are created from this template.
    Only one of nodeTypeFlexibility and nodeType can be specified.
    """
    nodeTypeFlexibility: Optional[List[NodeTypeFlexibilityItem]] = None
    """
    Flexible properties for the desired node type. Node groups that
    use this node template will create nodes of a type that matches
    these properties. Only one of nodeTypeFlexibility and nodeType can
    be specified.
    Structure is documented below.
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    region: str
    """
    Region where nodes using the node template will be created.
    If it is not provided, the provider region is used.
    """
    serverBinding: Optional[List[ServerBindingItem]] = None
    """
    The server binding policy for nodes using this template. Determines
    where the nodes should restart following a maintenance event.
    Structure is documented below.
    """


class InitProvider(BaseModel):
    accelerators: Optional[List[Accelerator]] = None
    """
    List of the type and count of accelerator cards attached to the
    node template
    Structure is documented below.
    """
    cpuOvercommitType: Optional[str] = None
    """
    CPU overcommit.
    Default value is NONE.
    Possible values are: ENABLED, NONE.
    """
    description: Optional[str] = None
    """
    An optional textual description of the resource.
    """
    disks: Optional[List[Disk]] = None
    """
    List of the type, size and count of disks attached to the
    node template
    Structure is documented below.
    """
    nodeAffinityLabels: Optional[Dict[str, str]] = None
    """
    Labels to use for node affinity, which will be used in
    instance scheduling.
    """
    nodeType: Optional[str] = None
    """
    Node type to use for nodes group that are created from this template.
    Only one of nodeTypeFlexibility and nodeType can be specified.
    """
    nodeTypeFlexibility: Optional[List[NodeTypeFlexibilityItem]] = None
    """
    Flexible properties for the desired node type. Node groups that
    use this node template will create nodes of a type that matches
    these properties. Only one of nodeTypeFlexibility and nodeType can
    be specified.
    Structure is documented below.
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    serverBinding: Optional[List[ServerBindingItem]] = None
    """
    The server binding policy for nodes using this template. Determines
    where the nodes should restart following a maintenance event.
    Structure is documented below.
    """


class Policy(BaseModel):
    resolution: Optional[Literal['Required', 'Optional']] = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Optional[Literal['Always', 'IfNotPresent']] = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Optional[Literal['Orphan', 'Delete']] = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: Optional[InitProvider] = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: Optional[
        List[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
    ] = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: Optional[ProviderConfigRef] = Field(
        default_factory=lambda: ProviderConfigRef.model_validate({'name': 'default'})
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: Optional[WriteConnectionSecretToRef] = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class NodeTypeFlexibilityItemModel(BaseModel):
    cpus: Optional[str] = None
    """
    Number of virtual CPUs to use.
    """
    localSsd: Optional[str] = None
    """
    (Output)
    Use local SSD
    """
    memory: Optional[str] = None
    """
    Physical memory available to the node, defined in MB.
    """


class AtProvider(BaseModel):
    accelerators: Optional[List[Accelerator]] = None
    """
    List of the type and count of accelerator cards attached to the
    node template
    Structure is documented below.
    """
    cpuOvercommitType: Optional[str] = None
    """
    CPU overcommit.
    Default value is NONE.
    Possible values are: ENABLED, NONE.
    """
    creationTimestamp: Optional[str] = None
    """
    Creation timestamp in RFC3339 text format.
    """
    description: Optional[str] = None
    """
    An optional textual description of the resource.
    """
    disks: Optional[List[Disk]] = None
    """
    List of the type, size and count of disks attached to the
    node template
    Structure is documented below.
    """
    id: Optional[str] = None
    """
    an identifier for the resource with format projects/{{project}}/regions/{{region}}/nodeTemplates/{{name}}
    """
    nodeAffinityLabels: Optional[Dict[str, str]] = None
    """
    Labels to use for node affinity, which will be used in
    instance scheduling.
    """
    nodeType: Optional[str] = None
    """
    Node type to use for nodes group that are created from this template.
    Only one of nodeTypeFlexibility and nodeType can be specified.
    """
    nodeTypeFlexibility: Optional[List[NodeTypeFlexibilityItemModel]] = None
    """
    Flexible properties for the desired node type. Node groups that
    use this node template will create nodes of a type that matches
    these properties. Only one of nodeTypeFlexibility and nodeType can
    be specified.
    Structure is documented below.
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    region: Optional[str] = None
    """
    Region where nodes using the node template will be created.
    If it is not provided, the provider region is used.
    """
    selfLink: Optional[str] = None
    """
    The URI of the created resource.
    """
    serverBinding: Optional[List[ServerBindingItem]] = None
    """
    The server binding policy for nodes using this template. Determines
    where the nodes should restart following a maintenance event.
    Structure is documented below.
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: Optional[str] = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: Optional[AtProvider] = None
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class NodeTemplate(BaseModel):
    apiVersion: Optional[Literal['compute.gcp.upbound.io/v1beta1']] = (
        'compute.gcp.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['NodeTemplate']] = 'NodeTemplate'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    NodeTemplateSpec defines the desired state of NodeTemplate
    """
    status: Optional[Status] = None
    """
    NodeTemplateStatus defines the observed state of NodeTemplate.
    """


class NodeTemplateList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[NodeTemplate]
    """
    List of nodetemplates. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """