apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: servingstacks.infrastructure.modelplane.ai
spec:
  compositeTypeRef:
    apiVersion: infrastructure.modelplane.ai/v1alpha1
    kind: ServingStack
  mode: Pipeline
  pipeline:
  - functionRef:
      name: modelplane-modelplanecompose-serving-stack
    step: compose-serving-stack
