# generated by datamodel-codegen:
#   filename:  workdir/compute_gcp_m_upbound_io_v1beta1_routerpeer.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class AdvertisedIpRange(BaseModel):
    description: str | None = None
    """
    User-specified description for the IP range.
    """
    range: str | None = None
    """
    The IP range to advertise. The value must be a
    CIDR-formatted string.
    """


class Bfd(BaseModel):
    minReceiveInterval: float | None = None
    """
    The minimum interval, in milliseconds, between BFD control packets
    received from the peer router. The actual value is negotiated
    between the two routers and is equal to the greater of this value
    and the transmit interval of the other router. If set, this value
    must be between 1000 and 30000.
    """
    minTransmitInterval: float | None = None
    """
    The minimum interval, in milliseconds, between BFD control packets
    transmitted to the peer router. The actual value is negotiated
    between the two routers and is equal to the greater of this value
    and the corresponding receive interval of the other router. If set,
    this value must be between 1000 and 30000.
    """
    multiplier: float | None = None
    """
    The number of consecutive BFD packets that must be missed before
    BFD declares that a peer is unavailable. If set, the value must
    be a value between 5 and 16.
    """
    sessionInitializationMode: str | None = None
    """
    The BFD session initialization mode for this BGP peer.
    If set to ACTIVE, the Cloud Router will initiate the BFD session
    for this BGP peer. If set to PASSIVE, the Cloud Router will wait
    for the peer router to initiate the BFD session for this BGP peer.
    If set to DISABLED, BFD is disabled for this BGP peer.
    Possible values are: ACTIVE, DISABLED, PASSIVE.
    """


class CustomLearnedIpRange(BaseModel):
    range: str | None = None
    """
    The IP range to learn. The value must be a
    CIDR-formatted string.
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class InterfaceRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class InterfaceSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class KeySecretRef(BaseModel):
    key: str
    name: str
    """
    Name of the secret.
    """


class Md5AuthenticationKey(BaseModel):
    keySecretRef: KeySecretRef | None = None
    """
    The MD5 authentication key for this BGP peer. Maximum length is 80 characters. Can only contain printable ASCII characters
    """
    name: str | None = None
    """
    Name used to identify the key. Must be unique within a router. Must comply with RFC1035.
    """


class PeerIpAddressRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class PeerIpAddressSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class RegionRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class RegionSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class RouterApplianceInstanceRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class RouterApplianceInstanceSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class RouterRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class RouterSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    advertiseMode: str | None = None
    """
    User-specified flag to indicate which mode to use for advertisement.
    Valid values of this enum field are: DEFAULT, CUSTOM
    Default value is DEFAULT.
    Possible values are: DEFAULT, CUSTOM.
    """
    advertisedGroups: list[str] | None = None
    """
    User-specified list of prefix groups to advertise in custom
    mode, which currently supports the following option:
    """
    advertisedIpRanges: list[AdvertisedIpRange] | None = None
    """
    User-specified list of individual IP ranges to advertise in
    custom mode. This field can only be populated if advertiseMode
    is CUSTOM and is advertised to all peers of the router. These IP
    ranges will be advertised in addition to any specified groups.
    Leave this field blank to advertise no custom IP ranges.
    Structure is documented below.
    """
    advertisedRoutePriority: float | None = None
    """
    The priority of routes advertised to this BGP peer.
    Where there is more than one matching route of maximum
    length, the routes with the lowest priority value win.
    """
    bfd: Bfd | None = None
    """
    BFD configuration for the BGP peering.
    Structure is documented below.
    """
    customLearnedIpRanges: list[CustomLearnedIpRange] | None = None
    """
    The custom learned route IP address range. Must be a valid CIDR-formatted prefix.
    If an IP address is provided without a subnet mask, it is interpreted as, for IPv4,
    a /32 singular IP address range, and, for IPv6, /128.
    Structure is documented below.
    """
    customLearnedRoutePriority: float | None = None
    """
    The user-defined custom learned route priority for a BGP session.
    This value is applied to all custom learned route ranges for the session.
    You can choose a value from 0 to 65335. If you don't provide a value,
    Google Cloud assigns a priority of 100 to the ranges.
    """
    enable: bool | None = None
    """
    The status of the BGP peer connection. If set to false, any active session
    with the peer is terminated and all associated routing information is removed.
    If set to true, the peer connection can be established with routing information.
    The default is true.
    """
    enableIpv4: bool | None = None
    """
    Enable IPv4 traffic over BGP Peer. It is enabled by default if the peerIpAddress is version 4.
    """
    enableIpv6: bool | None = None
    """
    Enable IPv6 traffic over BGP Peer. If not specified, it is disabled by default.
    """
    exportPolicies: list[str] | None = None
    """
    routers.list of export policies applied to this peer, in the order they must be evaluated.
    The name must correspond to an existing policy that has ROUTE_POLICY_TYPE_EXPORT type.
    """
    importPolicies: list[str] | None = None
    """
    routers.list of import policies applied to this peer, in the order they must be evaluated.
    The name must correspond to an existing policy that has ROUTE_POLICY_TYPE_IMPORT type.
    """
    interface: str | None = None
    """
    Name of the interface the BGP peer is associated with.
    """
    interfaceRef: InterfaceRef | None = None
    """
    Reference to a RouterInterface in compute to populate interface.
    """
    interfaceSelector: InterfaceSelector | None = None
    """
    Selector for a RouterInterface in compute to populate interface.
    """
    ipAddress: str | None = None
    """
    IP address of the interface inside Google Cloud Platform.
    Only IPv4 is supported.
    """
    ipv4NexthopAddress: str | None = None
    """
    IPv4 address of the interface inside Google Cloud Platform.
    """
    ipv6NexthopAddress: str | None = None
    """
    IPv6 address of the interface inside Google Cloud Platform.
    The address must be in the range 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64.
    If you do not specify the next hop addresses, Google Cloud automatically
    assigns unused addresses from the 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64 range for you.
    """
    md5AuthenticationKey: Md5AuthenticationKey | None = None
    """
    Configuration for MD5 authentication on the BGP session.
    Structure is documented below.
    """
    peerAsn: float | None = None
    """
    Peer BGP Autonomous System Number (ASN).
    Each BGP interface may use a different value.
    """
    peerIpAddress: str | None = None
    """
    IP address of the BGP interface outside Google Cloud Platform.
    Only IPv4 is supported. Required if ip_address is set.
    """
    peerIpAddressRef: PeerIpAddressRef | None = None
    """
    Reference to a Address in compute to populate peerIpAddress.
    """
    peerIpAddressSelector: PeerIpAddressSelector | None = None
    """
    Selector for a Address in compute to populate peerIpAddress.
    """
    peerIpv4NexthopAddress: str | None = None
    """
    IPv4 address of the BGP interface outside Google Cloud Platform.
    """
    peerIpv6NexthopAddress: str | None = None
    """
    IPv6 address of the BGP interface outside Google Cloud Platform.
    The address must be in the range 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64.
    If you do not specify the next hop addresses, Google Cloud automatically
    assigns unused addresses from the 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64 range for you.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    region: str | None = None
    """
    Region where the router and BgpPeer reside.
    If it is not provided, the provider region is used.
    """
    regionRef: RegionRef | None = None
    """
    Reference to a Router in compute to populate region.
    """
    regionSelector: RegionSelector | None = None
    """
    Selector for a Router in compute to populate region.
    """
    router: str | None = None
    """
    The name of the Cloud Router in which this BgpPeer will be configured.
    """
    routerApplianceInstance: str | None = None
    """
    The URI of the VM instance that is used as third-party router appliances
    such as Next Gen Firewalls, Virtual Routers, or Router Appliances.
    The VM instance must be located in zones contained in the same region as
    this Cloud Router. The VM instance is the peer side of the BGP session.
    """
    routerApplianceInstanceRef: RouterApplianceInstanceRef | None = None
    """
    Reference to a Instance in compute to populate routerApplianceInstance.
    """
    routerApplianceInstanceSelector: RouterApplianceInstanceSelector | None = None
    """
    Selector for a Instance in compute to populate routerApplianceInstance.
    """
    routerRef: RouterRef | None = None
    """
    Reference to a Router in compute to populate router.
    """
    routerSelector: RouterSelector | None = None
    """
    Selector for a Router in compute to populate router.
    """
    zeroAdvertisedRoutePriority: bool | None = None
    """
    The user-defined zero-advertised-route-priority for a advertised-route-priority in BGP session.
    This value has to be set true to force the advertised_route_priority to be 0.
    """
    zeroCustomLearnedRoutePriority: bool | None = None
    """
    The user-defined zero-custom-learned-route-priority for a custom-learned-route-priority in BGP session.
    This value has to be set true to force the custom_learned_route_priority to be 0.
    """


class Md5AuthenticationKeyModel(BaseModel):
    keySecretRef: KeySecretRef
    """
    The MD5 authentication key for this BGP peer. Maximum length is 80 characters. Can only contain printable ASCII characters
    """
    name: str | None = None
    """
    Name used to identify the key. Must be unique within a router. Must comply with RFC1035.
    """


class InitProvider(BaseModel):
    advertiseMode: str | None = None
    """
    User-specified flag to indicate which mode to use for advertisement.
    Valid values of this enum field are: DEFAULT, CUSTOM
    Default value is DEFAULT.
    Possible values are: DEFAULT, CUSTOM.
    """
    advertisedGroups: list[str] | None = None
    """
    User-specified list of prefix groups to advertise in custom
    mode, which currently supports the following option:
    """
    advertisedIpRanges: list[AdvertisedIpRange] | None = None
    """
    User-specified list of individual IP ranges to advertise in
    custom mode. This field can only be populated if advertiseMode
    is CUSTOM and is advertised to all peers of the router. These IP
    ranges will be advertised in addition to any specified groups.
    Leave this field blank to advertise no custom IP ranges.
    Structure is documented below.
    """
    advertisedRoutePriority: float | None = None
    """
    The priority of routes advertised to this BGP peer.
    Where there is more than one matching route of maximum
    length, the routes with the lowest priority value win.
    """
    bfd: Bfd | None = None
    """
    BFD configuration for the BGP peering.
    Structure is documented below.
    """
    customLearnedIpRanges: list[CustomLearnedIpRange] | None = None
    """
    The custom learned route IP address range. Must be a valid CIDR-formatted prefix.
    If an IP address is provided without a subnet mask, it is interpreted as, for IPv4,
    a /32 singular IP address range, and, for IPv6, /128.
    Structure is documented below.
    """
    customLearnedRoutePriority: float | None = None
    """
    The user-defined custom learned route priority for a BGP session.
    This value is applied to all custom learned route ranges for the session.
    You can choose a value from 0 to 65335. If you don't provide a value,
    Google Cloud assigns a priority of 100 to the ranges.
    """
    enable: bool | None = None
    """
    The status of the BGP peer connection. If set to false, any active session
    with the peer is terminated and all associated routing information is removed.
    If set to true, the peer connection can be established with routing information.
    The default is true.
    """
    enableIpv4: bool | None = None
    """
    Enable IPv4 traffic over BGP Peer. It is enabled by default if the peerIpAddress is version 4.
    """
    enableIpv6: bool | None = None
    """
    Enable IPv6 traffic over BGP Peer. If not specified, it is disabled by default.
    """
    exportPolicies: list[str] | None = None
    """
    routers.list of export policies applied to this peer, in the order they must be evaluated.
    The name must correspond to an existing policy that has ROUTE_POLICY_TYPE_EXPORT type.
    """
    importPolicies: list[str] | None = None
    """
    routers.list of import policies applied to this peer, in the order they must be evaluated.
    The name must correspond to an existing policy that has ROUTE_POLICY_TYPE_IMPORT type.
    """
    interface: str | None = None
    """
    Name of the interface the BGP peer is associated with.
    """
    interfaceRef: InterfaceRef | None = None
    """
    Reference to a RouterInterface in compute to populate interface.
    """
    interfaceSelector: InterfaceSelector | None = None
    """
    Selector for a RouterInterface in compute to populate interface.
    """
    ipAddress: str | None = None
    """
    IP address of the interface inside Google Cloud Platform.
    Only IPv4 is supported.
    """
    ipv4NexthopAddress: str | None = None
    """
    IPv4 address of the interface inside Google Cloud Platform.
    """
    ipv6NexthopAddress: str | None = None
    """
    IPv6 address of the interface inside Google Cloud Platform.
    The address must be in the range 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64.
    If you do not specify the next hop addresses, Google Cloud automatically
    assigns unused addresses from the 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64 range for you.
    """
    md5AuthenticationKey: Md5AuthenticationKeyModel | None = None
    """
    Configuration for MD5 authentication on the BGP session.
    Structure is documented below.
    """
    peerAsn: float | None = None
    """
    Peer BGP Autonomous System Number (ASN).
    Each BGP interface may use a different value.
    """
    peerIpAddress: str | None = None
    """
    IP address of the BGP interface outside Google Cloud Platform.
    Only IPv4 is supported. Required if ip_address is set.
    """
    peerIpAddressRef: PeerIpAddressRef | None = None
    """
    Reference to a Address in compute to populate peerIpAddress.
    """
    peerIpAddressSelector: PeerIpAddressSelector | None = None
    """
    Selector for a Address in compute to populate peerIpAddress.
    """
    peerIpv4NexthopAddress: str | None = None
    """
    IPv4 address of the BGP interface outside Google Cloud Platform.
    """
    peerIpv6NexthopAddress: str | None = None
    """
    IPv6 address of the BGP interface outside Google Cloud Platform.
    The address must be in the range 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64.
    If you do not specify the next hop addresses, Google Cloud automatically
    assigns unused addresses from the 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64 range for you.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    region: str | None = None
    """
    Region where the router and BgpPeer reside.
    If it is not provided, the provider region is used.
    """
    regionRef: RegionRef | None = None
    """
    Reference to a Router in compute to populate region.
    """
    regionSelector: RegionSelector | None = None
    """
    Selector for a Router in compute to populate region.
    """
    routerApplianceInstance: str | None = None
    """
    The URI of the VM instance that is used as third-party router appliances
    such as Next Gen Firewalls, Virtual Routers, or Router Appliances.
    The VM instance must be located in zones contained in the same region as
    this Cloud Router. The VM instance is the peer side of the BGP session.
    """
    routerApplianceInstanceRef: RouterApplianceInstanceRef | None = None
    """
    Reference to a Instance in compute to populate routerApplianceInstance.
    """
    routerApplianceInstanceSelector: RouterApplianceInstanceSelector | None = None
    """
    Selector for a Instance in compute to populate routerApplianceInstance.
    """
    zeroAdvertisedRoutePriority: bool | None = None
    """
    The user-defined zero-advertised-route-priority for a advertised-route-priority in BGP session.
    This value has to be set true to force the advertised_route_priority to be 0.
    """
    zeroCustomLearnedRoutePriority: bool | None = None
    """
    The user-defined zero-custom-learned-route-priority for a custom-learned-route-priority in BGP session.
    This value has to be set true to force the custom_learned_route_priority to be 0.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class Md5AuthenticationKeyModel1(BaseModel):
    name: str | None = None
    """
    Name used to identify the key. Must be unique within a router. Must comply with RFC1035.
    """


class AtProvider(BaseModel):
    advertiseMode: str | None = None
    """
    User-specified flag to indicate which mode to use for advertisement.
    Valid values of this enum field are: DEFAULT, CUSTOM
    Default value is DEFAULT.
    Possible values are: DEFAULT, CUSTOM.
    """
    advertisedGroups: list[str] | None = None
    """
    User-specified list of prefix groups to advertise in custom
    mode, which currently supports the following option:
    """
    advertisedIpRanges: list[AdvertisedIpRange] | None = None
    """
    User-specified list of individual IP ranges to advertise in
    custom mode. This field can only be populated if advertiseMode
    is CUSTOM and is advertised to all peers of the router. These IP
    ranges will be advertised in addition to any specified groups.
    Leave this field blank to advertise no custom IP ranges.
    Structure is documented below.
    """
    advertisedRoutePriority: float | None = None
    """
    The priority of routes advertised to this BGP peer.
    Where there is more than one matching route of maximum
    length, the routes with the lowest priority value win.
    """
    bfd: Bfd | None = None
    """
    BFD configuration for the BGP peering.
    Structure is documented below.
    """
    customLearnedIpRanges: list[CustomLearnedIpRange] | None = None
    """
    The custom learned route IP address range. Must be a valid CIDR-formatted prefix.
    If an IP address is provided without a subnet mask, it is interpreted as, for IPv4,
    a /32 singular IP address range, and, for IPv6, /128.
    Structure is documented below.
    """
    customLearnedRoutePriority: float | None = None
    """
    The user-defined custom learned route priority for a BGP session.
    This value is applied to all custom learned route ranges for the session.
    You can choose a value from 0 to 65335. If you don't provide a value,
    Google Cloud assigns a priority of 100 to the ranges.
    """
    enable: bool | None = None
    """
    The status of the BGP peer connection. If set to false, any active session
    with the peer is terminated and all associated routing information is removed.
    If set to true, the peer connection can be established with routing information.
    The default is true.
    """
    enableIpv4: bool | None = None
    """
    Enable IPv4 traffic over BGP Peer. It is enabled by default if the peerIpAddress is version 4.
    """
    enableIpv6: bool | None = None
    """
    Enable IPv6 traffic over BGP Peer. If not specified, it is disabled by default.
    """
    exportPolicies: list[str] | None = None
    """
    routers.list of export policies applied to this peer, in the order they must be evaluated.
    The name must correspond to an existing policy that has ROUTE_POLICY_TYPE_EXPORT type.
    """
    id: str | None = None
    """
    an identifier for the resource with format projects/{{project}}/regions/{{region}}/routers/{{router}}/{{name}}
    """
    importPolicies: list[str] | None = None
    """
    routers.list of import policies applied to this peer, in the order they must be evaluated.
    The name must correspond to an existing policy that has ROUTE_POLICY_TYPE_IMPORT type.
    """
    interface: str | None = None
    """
    Name of the interface the BGP peer is associated with.
    """
    ipAddress: str | None = None
    """
    IP address of the interface inside Google Cloud Platform.
    Only IPv4 is supported.
    """
    ipv4NexthopAddress: str | None = None
    """
    IPv4 address of the interface inside Google Cloud Platform.
    """
    ipv6NexthopAddress: str | None = None
    """
    IPv6 address of the interface inside Google Cloud Platform.
    The address must be in the range 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64.
    If you do not specify the next hop addresses, Google Cloud automatically
    assigns unused addresses from the 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64 range for you.
    """
    isAdvertisedRoutePrioritySet: bool | None = None
    isCustomLearnedPrioritySet: bool | None = None
    managementType: str | None = None
    """
    The resource that configures and manages this BGP peer.
    """
    md5AuthenticationKey: Md5AuthenticationKeyModel1 | None = None
    """
    Configuration for MD5 authentication on the BGP session.
    Structure is documented below.
    """
    peerAsn: float | None = None
    """
    Peer BGP Autonomous System Number (ASN).
    Each BGP interface may use a different value.
    """
    peerIpAddress: str | None = None
    """
    IP address of the BGP interface outside Google Cloud Platform.
    Only IPv4 is supported. Required if ip_address is set.
    """
    peerIpv4NexthopAddress: str | None = None
    """
    IPv4 address of the BGP interface outside Google Cloud Platform.
    """
    peerIpv6NexthopAddress: str | None = None
    """
    IPv6 address of the BGP interface outside Google Cloud Platform.
    The address must be in the range 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64.
    If you do not specify the next hop addresses, Google Cloud automatically
    assigns unused addresses from the 2600:2d00:0:2::/64 or 2600:2d00:0:3::/64 range for you.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    region: str | None = None
    """
    Region where the router and BgpPeer reside.
    If it is not provided, the provider region is used.
    """
    router: str | None = None
    """
    The name of the Cloud Router in which this BgpPeer will be configured.
    """
    routerApplianceInstance: str | None = None
    """
    The URI of the VM instance that is used as third-party router appliances
    such as Next Gen Firewalls, Virtual Routers, or Router Appliances.
    The VM instance must be located in zones contained in the same region as
    this Cloud Router. The VM instance is the peer side of the BGP session.
    """
    zeroAdvertisedRoutePriority: bool | None = None
    """
    The user-defined zero-advertised-route-priority for a advertised-route-priority in BGP session.
    This value has to be set true to force the advertised_route_priority to be 0.
    """
    zeroCustomLearnedRoutePriority: bool | None = None
    """
    The user-defined zero-custom-learned-route-priority for a custom-learned-route-priority in BGP session.
    This value has to be set true to force the custom_learned_route_priority to be 0.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class RouterPeer(BaseModel):
    apiVersion: Literal['compute.gcp.m.upbound.io/v1beta1'] | None = (
        'compute.gcp.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['RouterPeer'] | None = 'RouterPeer'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    RouterPeerSpec defines the desired state of RouterPeer
    """
    status: Status | None = None
    """
    RouterPeerStatus defines the observed state of RouterPeer.
    """


class RouterPeerList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[RouterPeer]
    """
    List of routerpeers. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """