# generated by datamodel-codegen:
#   filename:  workdir/infrastructure_modelplane_ai_v1alpha1_servingstack.yaml

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field, conint, constr

from .....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: Dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: Dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: Optional[str] = None


class Crossplane(BaseModel):
    compositionRef: Optional[CompositionRef] = None
    compositionRevisionRef: Optional[CompositionRevisionRef] = None
    compositionRevisionSelector: Optional[CompositionRevisionSelector] = None
    compositionSelector: Optional[CompositionSelector] = None
    compositionUpdatePolicy: Optional[Literal['Automatic', 'Manual']] = None
    resourceRefs: Optional[List[ResourceRef]] = None


class Listener(BaseModel):
    name: constr(min_length=1, max_length=63)
    """
    Unique listener name.
    """
    port: conint(ge=1, le=65535)
    """
    Port number for this listener.
    """
    protocol: Literal['HTTP', 'TCP']
    """
    Protocol for this listener.
    """


class Gateway(BaseModel):
    className: Optional[constr(min_length=1, max_length=63)] = 'envoy'
    """
    GatewayClass name. Override if the cluster already has a GatewayClass named envoy.
    """
    listeners: Optional[List[Listener]] = Field(None, max_length=8)
    """
    Gateway listeners. Defaults to a single HTTP listener on port 80 if not specified.
    """


class Secret(BaseModel):
    key: constr(max_length=253)
    """
    Key within the Secret that holds the credential data.
    """
    name: constr(max_length=253)
    """
    Name of the Secret.
    """
    type: Literal['Kubeconfig', 'GCPServiceAccountKey']
    """
    The type of credential this secret contains. Kubeconfig is required. Cloud-specific types are optional and determine how the ProviderConfigs authenticate.
    """


class Versions(BaseModel):
    certManager: Optional[constr(min_length=1, max_length=32)] = 'v1.17.1'
    """
    cert-manager chart version.
    """
    envoyGateway: Optional[constr(min_length=1, max_length=32)] = 'v1.3.0'
    """
    Envoy Gateway chart version.
    """
    gatewayApi: Optional[constr(min_length=1, max_length=32)] = 'v1.5.1'
    """
    Gateway API CRD version.
    """
    leaderWorkerSet: Optional[constr(min_length=1, max_length=32)] = 'v0.8.0'
    """
    LeaderWorkerSet chart version.
    """
    prometheus: Optional[constr(min_length=1, max_length=32)] = '72.6.2'
    """
    kube-prometheus-stack chart version.
    """


class Spec(BaseModel):
    crossplane: Optional[Crossplane] = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    gateway: Optional[Gateway] = None
    """
    Configuration for the cluster's inference traffic gateway.
    """
    secrets: List[Secret] = Field(..., min_length=1)
    """
    Secrets used to authenticate to the target cluster. Typically sourced from a GKECluster's status.secrets. All secrets must be in the same namespace as this ServingStack. A Kubeconfig secret is required. If a cloud-specific credential secret is present (e.g. GCPServiceAccountKey), the ProviderConfigs will use it for identity-based authentication instead of relying on the kubeconfig's embedded credentials.
    """
    versions: Optional[Versions] = None
    """
    Version pins for each component. Defaults are the latest tested combination. Override individual versions to upgrade components independently.
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    message: Optional[str] = None
    observedGeneration: Optional[int] = None
    reason: str
    status: str
    type: str


class GatewayModel(BaseModel):
    address: Optional[constr(max_length=256)] = None
    """
    The gateway's external address, once assigned by the cloud load balancer.
    """


class Status(BaseModel):
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    gateway: Optional[GatewayModel] = None
    """
    Status of the cluster's inference gateway.
    """


class ServingStack(BaseModel):
    apiVersion: Optional[Literal['infrastructure.modelplane.ai/v1alpha1']] = (
        'infrastructure.modelplane.ai/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['ServingStack']] = 'ServingStack'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    ServingStackSpec defines the desired state of ServingStack.
    """
    status: Optional[Status] = None
    """
    ServingStackStatus defines the observed state of ServingStack.
    """


class ServingStackList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[ServingStack]
    """
    List of servingstacks. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """