# generated by datamodel-codegen:
#   filename:  workdir/compute_gcp_upbound_io_v1beta2_forwardingrule.yaml

from __future__ import annotations

from datetime import datetime
from typing import Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Optional[Literal['Required', 'Optional']] = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Optional[Literal['Always', 'IfNotPresent']] = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class BackendServiceRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class BackendServiceSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class IpAddressRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class IpAddressSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class NetworkRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class NetworkSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class ServiceDirectoryRegistrations(BaseModel):
    namespace: Optional[str] = None
    """
    Service Directory namespace to register the forwarding rule under.
    """
    service: Optional[str] = None
    """
    Service Directory service to register the forwarding rule under.
    """


class SubnetworkRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class SubnetworkSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class TargetRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class TargetSelector(BaseModel):
    matchControllerRef: Optional[bool] = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Optional[Policy] = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    allPorts: Optional[bool] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The allPorts field has the following limitations:
    """
    allowGlobalAccess: Optional[bool] = None
    """
    This field is used along with the backend_service field for
    internal load balancing or with the target field for internal
    TargetInstance.
    If the field is set to TRUE, clients can access ILB from all
    regions.
    Otherwise only allows access from clients in the same region as the
    internal load balancer.
    """
    allowPscGlobalAccess: Optional[bool] = None
    """
    This is used in PSC consumer ForwardingRule to control whether the PSC endpoint can be accessed from another region.
    """
    backendService: Optional[str] = None
    """
    Identifies the backend service to which the forwarding rule sends traffic.
    Required for Internal TCP/UDP Load Balancing and Network Load Balancing;
    must be omitted for all other load balancer types.
    """
    backendServiceRef: Optional[BackendServiceRef] = None
    """
    Reference to a RegionBackendService in compute to populate backendService.
    """
    backendServiceSelector: Optional[BackendServiceSelector] = None
    """
    Selector for a RegionBackendService in compute to populate backendService.
    """
    description: Optional[str] = None
    """
    An optional description of this resource. Provide this property when
    you create the resource.
    """
    ipAddress: Optional[str] = None
    """
    IP address for which this forwarding rule accepts traffic. When a client
    sends traffic to this IP address, the forwarding rule directs the traffic
    to the referenced target or backendService.
    While creating a forwarding rule, specifying an IPAddress is
    required under the following circumstances:
    """
    ipAddressRef: Optional[IpAddressRef] = None
    """
    Reference to a Address in compute to populate ipAddress.
    """
    ipAddressSelector: Optional[IpAddressSelector] = None
    """
    Selector for a Address in compute to populate ipAddress.
    """
    ipCollection: Optional[str] = None
    """
    Resource reference of a PublicDelegatedPrefix. The PDP must be a sub-PDP
    in EXTERNAL_IPV6_FORWARDING_RULE_CREATION mode.
    Use one of the following formats to specify a sub-PDP when creating an
    IPv6 NetLB forwarding rule using BYOIP:
    Full resource URL, as in:
    """
    ipProtocol: Optional[str] = None
    """
    The IP protocol to which this rule applies.
    For protocol forwarding, valid
    options are TCP, UDP, ESP,
    AH, SCTP, ICMP and
    L3_DEFAULT.
    The valid IP protocols are different for different load balancing products
    as described in Load balancing
    features.
    A Forwarding Rule with protocol L3_DEFAULT can attach with target instance or
    backend service with UNSPECIFIED protocol.
    A forwarding rule with "L3_DEFAULT" IPProtocal cannot be attached to a backend service with TCP or UDP.
    Possible values are: TCP, UDP, ESP, AH, SCTP, ICMP, L3_DEFAULT.
    """
    ipVersion: Optional[str] = None
    """
    The IP address version that will be used by this forwarding rule.
    Valid options are IPV4 and IPV6.
    If not set, the IPv4 address will be used by default.
    Possible values are: IPV4, IPV6.
    """
    isMirroringCollector: Optional[bool] = None
    """
    Indicates whether or not this load balancer can be used as a collector for
    packet mirroring. To prevent mirroring loops, instances behind this
    load balancer will not have their traffic mirrored even if a
    PacketMirroring rule applies to them.
    This can only be set to true for load balancers that have their
    loadBalancingScheme set to INTERNAL.
    """
    labels: Optional[Dict[str, str]] = None
    """
    Labels to apply to this forwarding rule.  A list of key->value pairs.
    """
    loadBalancingScheme: Optional[str] = None
    """
    Specifies the forwarding rule type.
    Note that an empty string value ("") is also supported for some use
    cases, for example PSC (private service connection) regional forwarding
    rules.
    For more information about forwarding rules, refer to
    Forwarding rule concepts.
    Default value is EXTERNAL.
    Possible values are: EXTERNAL, EXTERNAL_MANAGED, INTERNAL, INTERNAL_MANAGED.
    """
    network: Optional[str] = None
    """
    This field is not used for external load balancing.
    For Internal TCP/UDP Load Balancing, this field identifies the network that
    the load balanced IP should belong to for this Forwarding Rule.
    If the subnetwork is specified, the network of the subnetwork will be used.
    If neither subnetwork nor this field is specified, the default network will
    be used.
    For Private Service Connect forwarding rules that forward traffic to Google
    APIs, a network must be provided.
    """
    networkRef: Optional[NetworkRef] = None
    """
    Reference to a Network in compute to populate network.
    """
    networkSelector: Optional[NetworkSelector] = None
    """
    Selector for a Network in compute to populate network.
    """
    networkTier: Optional[str] = None
    """
    This signifies the networking tier used for configuring
    this load balancer and can only take the following values:
    PREMIUM, STANDARD.
    For regional ForwardingRule, the valid values are PREMIUM and
    STANDARD. For GlobalForwardingRule, the valid value is
    PREMIUM.
    If this field is not specified, it is assumed to be PREMIUM.
    If IPAddress is specified, this value must be equal to the
    networkTier of the Address.
    Possible values are: PREMIUM, STANDARD.
    """
    noAutomateDnsZone: Optional[bool] = None
    """
    This is used in PSC consumer ForwardingRule to control whether it should try to auto-generate a DNS zone or not. Non-PSC forwarding rules do not use this field.
    """
    portRange: Optional[str] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The portRange field has the following limitations:
    """
    ports: Optional[List[str]] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The ports field has the following limitations:
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    recreateClosedPsc: Optional[bool] = None
    """
    this is used in psc consumer forwardingrule to make provider recreate the forwardingrule when the status is closed
    """
    region: str
    """
    A reference to the region where the regional forwarding rule resides.
    This field is not applicable to global forwarding rules.
    """
    serviceDirectoryRegistrations: Optional[ServiceDirectoryRegistrations] = None
    """
    Service Directory resources to register this forwarding rule with.
    Currently, only supports a single Service Directory resource.
    Structure is documented below.
    """
    serviceLabel: Optional[str] = None
    """
    An optional prefix to the service name for this Forwarding Rule.
    If specified, will be the first label of the fully qualified service
    name.
    The label must be 1-63 characters long, and comply with RFC1035.
    Specifically, the label must be 1-63 characters long and match the
    regular expression [a-z]([-a-z0-9]*[a-z0-9])? which means the first
    character must be a lowercase letter, and all following characters
    must be a dash, lowercase letter, or digit, except the last
    character, which cannot be a dash.
    This field is only used for INTERNAL load balancing.
    """
    sourceIpRanges: Optional[List[str]] = None
    """
    If not empty, this Forwarding Rule will only forward the traffic when the source IP address matches one of the IP addresses or CIDR ranges set here. Note that a Forwarding Rule can only have up to 64 source IP ranges, and this field can only be used with a regional Forwarding Rule whose scheme is EXTERNAL. Each sourceIpRange entry should be either an IP address (for example, 1.2.3.4) or a CIDR range (for example, 1.2.3.0/24).
    """
    subnetwork: Optional[str] = None
    """
    This field identifies the subnetwork that the load balanced IP should
    belong to for this Forwarding Rule, used in internal load balancing and
    network load balancing with IPv6.
    If the network specified is in auto subnet mode, this field is optional.
    However, a subnetwork must be specified if the network is in custom subnet
    mode or when creating external forwarding rule with IPv6.
    """
    subnetworkRef: Optional[SubnetworkRef] = None
    """
    Reference to a Subnetwork in compute to populate subnetwork.
    """
    subnetworkSelector: Optional[SubnetworkSelector] = None
    """
    Selector for a Subnetwork in compute to populate subnetwork.
    """
    target: Optional[str] = None
    """
    is set to targetGrpcProxy and
    validateForProxyless is set to true, the
    IPAddress should be set to 0.0.0.0.
    """
    targetRef: Optional[TargetRef] = None
    """
    Reference to a RegionTargetHTTPProxy in compute to populate target.
    """
    targetSelector: Optional[TargetSelector] = None
    """
    Selector for a RegionTargetHTTPProxy in compute to populate target.
    """


class InitProvider(BaseModel):
    allPorts: Optional[bool] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The allPorts field has the following limitations:
    """
    allowGlobalAccess: Optional[bool] = None
    """
    This field is used along with the backend_service field for
    internal load balancing or with the target field for internal
    TargetInstance.
    If the field is set to TRUE, clients can access ILB from all
    regions.
    Otherwise only allows access from clients in the same region as the
    internal load balancer.
    """
    allowPscGlobalAccess: Optional[bool] = None
    """
    This is used in PSC consumer ForwardingRule to control whether the PSC endpoint can be accessed from another region.
    """
    backendService: Optional[str] = None
    """
    Identifies the backend service to which the forwarding rule sends traffic.
    Required for Internal TCP/UDP Load Balancing and Network Load Balancing;
    must be omitted for all other load balancer types.
    """
    backendServiceRef: Optional[BackendServiceRef] = None
    """
    Reference to a RegionBackendService in compute to populate backendService.
    """
    backendServiceSelector: Optional[BackendServiceSelector] = None
    """
    Selector for a RegionBackendService in compute to populate backendService.
    """
    description: Optional[str] = None
    """
    An optional description of this resource. Provide this property when
    you create the resource.
    """
    ipAddress: Optional[str] = None
    """
    IP address for which this forwarding rule accepts traffic. When a client
    sends traffic to this IP address, the forwarding rule directs the traffic
    to the referenced target or backendService.
    While creating a forwarding rule, specifying an IPAddress is
    required under the following circumstances:
    """
    ipAddressRef: Optional[IpAddressRef] = None
    """
    Reference to a Address in compute to populate ipAddress.
    """
    ipAddressSelector: Optional[IpAddressSelector] = None
    """
    Selector for a Address in compute to populate ipAddress.
    """
    ipCollection: Optional[str] = None
    """
    Resource reference of a PublicDelegatedPrefix. The PDP must be a sub-PDP
    in EXTERNAL_IPV6_FORWARDING_RULE_CREATION mode.
    Use one of the following formats to specify a sub-PDP when creating an
    IPv6 NetLB forwarding rule using BYOIP:
    Full resource URL, as in:
    """
    ipProtocol: Optional[str] = None
    """
    The IP protocol to which this rule applies.
    For protocol forwarding, valid
    options are TCP, UDP, ESP,
    AH, SCTP, ICMP and
    L3_DEFAULT.
    The valid IP protocols are different for different load balancing products
    as described in Load balancing
    features.
    A Forwarding Rule with protocol L3_DEFAULT can attach with target instance or
    backend service with UNSPECIFIED protocol.
    A forwarding rule with "L3_DEFAULT" IPProtocal cannot be attached to a backend service with TCP or UDP.
    Possible values are: TCP, UDP, ESP, AH, SCTP, ICMP, L3_DEFAULT.
    """
    ipVersion: Optional[str] = None
    """
    The IP address version that will be used by this forwarding rule.
    Valid options are IPV4 and IPV6.
    If not set, the IPv4 address will be used by default.
    Possible values are: IPV4, IPV6.
    """
    isMirroringCollector: Optional[bool] = None
    """
    Indicates whether or not this load balancer can be used as a collector for
    packet mirroring. To prevent mirroring loops, instances behind this
    load balancer will not have their traffic mirrored even if a
    PacketMirroring rule applies to them.
    This can only be set to true for load balancers that have their
    loadBalancingScheme set to INTERNAL.
    """
    labels: Optional[Dict[str, str]] = None
    """
    Labels to apply to this forwarding rule.  A list of key->value pairs.
    """
    loadBalancingScheme: Optional[str] = None
    """
    Specifies the forwarding rule type.
    Note that an empty string value ("") is also supported for some use
    cases, for example PSC (private service connection) regional forwarding
    rules.
    For more information about forwarding rules, refer to
    Forwarding rule concepts.
    Default value is EXTERNAL.
    Possible values are: EXTERNAL, EXTERNAL_MANAGED, INTERNAL, INTERNAL_MANAGED.
    """
    network: Optional[str] = None
    """
    This field is not used for external load balancing.
    For Internal TCP/UDP Load Balancing, this field identifies the network that
    the load balanced IP should belong to for this Forwarding Rule.
    If the subnetwork is specified, the network of the subnetwork will be used.
    If neither subnetwork nor this field is specified, the default network will
    be used.
    For Private Service Connect forwarding rules that forward traffic to Google
    APIs, a network must be provided.
    """
    networkRef: Optional[NetworkRef] = None
    """
    Reference to a Network in compute to populate network.
    """
    networkSelector: Optional[NetworkSelector] = None
    """
    Selector for a Network in compute to populate network.
    """
    networkTier: Optional[str] = None
    """
    This signifies the networking tier used for configuring
    this load balancer and can only take the following values:
    PREMIUM, STANDARD.
    For regional ForwardingRule, the valid values are PREMIUM and
    STANDARD. For GlobalForwardingRule, the valid value is
    PREMIUM.
    If this field is not specified, it is assumed to be PREMIUM.
    If IPAddress is specified, this value must be equal to the
    networkTier of the Address.
    Possible values are: PREMIUM, STANDARD.
    """
    noAutomateDnsZone: Optional[bool] = None
    """
    This is used in PSC consumer ForwardingRule to control whether it should try to auto-generate a DNS zone or not. Non-PSC forwarding rules do not use this field.
    """
    portRange: Optional[str] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The portRange field has the following limitations:
    """
    ports: Optional[List[str]] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The ports field has the following limitations:
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    recreateClosedPsc: Optional[bool] = None
    """
    this is used in psc consumer forwardingrule to make provider recreate the forwardingrule when the status is closed
    """
    serviceDirectoryRegistrations: Optional[ServiceDirectoryRegistrations] = None
    """
    Service Directory resources to register this forwarding rule with.
    Currently, only supports a single Service Directory resource.
    Structure is documented below.
    """
    serviceLabel: Optional[str] = None
    """
    An optional prefix to the service name for this Forwarding Rule.
    If specified, will be the first label of the fully qualified service
    name.
    The label must be 1-63 characters long, and comply with RFC1035.
    Specifically, the label must be 1-63 characters long and match the
    regular expression [a-z]([-a-z0-9]*[a-z0-9])? which means the first
    character must be a lowercase letter, and all following characters
    must be a dash, lowercase letter, or digit, except the last
    character, which cannot be a dash.
    This field is only used for INTERNAL load balancing.
    """
    sourceIpRanges: Optional[List[str]] = None
    """
    If not empty, this Forwarding Rule will only forward the traffic when the source IP address matches one of the IP addresses or CIDR ranges set here. Note that a Forwarding Rule can only have up to 64 source IP ranges, and this field can only be used with a regional Forwarding Rule whose scheme is EXTERNAL. Each sourceIpRange entry should be either an IP address (for example, 1.2.3.4) or a CIDR range (for example, 1.2.3.0/24).
    """
    subnetwork: Optional[str] = None
    """
    This field identifies the subnetwork that the load balanced IP should
    belong to for this Forwarding Rule, used in internal load balancing and
    network load balancing with IPv6.
    If the network specified is in auto subnet mode, this field is optional.
    However, a subnetwork must be specified if the network is in custom subnet
    mode or when creating external forwarding rule with IPv6.
    """
    subnetworkRef: Optional[SubnetworkRef] = None
    """
    Reference to a Subnetwork in compute to populate subnetwork.
    """
    subnetworkSelector: Optional[SubnetworkSelector] = None
    """
    Selector for a Subnetwork in compute to populate subnetwork.
    """
    target: Optional[str] = None
    """
    is set to targetGrpcProxy and
    validateForProxyless is set to true, the
    IPAddress should be set to 0.0.0.0.
    """
    targetRef: Optional[TargetRef] = None
    """
    Reference to a RegionTargetHTTPProxy in compute to populate target.
    """
    targetSelector: Optional[TargetSelector] = None
    """
    Selector for a RegionTargetHTTPProxy in compute to populate target.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Optional[Literal['Orphan', 'Delete']] = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: Optional[InitProvider] = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: Optional[
        List[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
    ] = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: Optional[ProviderConfigRef] = Field(
        default_factory=lambda: ProviderConfigRef.model_validate({'name': 'default'})
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: Optional[WriteConnectionSecretToRef] = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    allPorts: Optional[bool] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The allPorts field has the following limitations:
    """
    allowGlobalAccess: Optional[bool] = None
    """
    This field is used along with the backend_service field for
    internal load balancing or with the target field for internal
    TargetInstance.
    If the field is set to TRUE, clients can access ILB from all
    regions.
    Otherwise only allows access from clients in the same region as the
    internal load balancer.
    """
    allowPscGlobalAccess: Optional[bool] = None
    """
    This is used in PSC consumer ForwardingRule to control whether the PSC endpoint can be accessed from another region.
    """
    backendService: Optional[str] = None
    """
    Identifies the backend service to which the forwarding rule sends traffic.
    Required for Internal TCP/UDP Load Balancing and Network Load Balancing;
    must be omitted for all other load balancer types.
    """
    baseForwardingRule: Optional[str] = None
    """
    [Output Only] The URL for the corresponding base Forwarding Rule. By base Forwarding Rule, we mean the Forwarding Rule that has the same IP address, protocol, and port settings with the current Forwarding Rule, but without sourceIPRanges specified. Always empty if the current Forwarding Rule does not have sourceIPRanges specified.
    """
    creationTimestamp: Optional[str] = None
    """
    Creation timestamp in RFC3339 text format.
    """
    description: Optional[str] = None
    """
    An optional description of this resource. Provide this property when
    you create the resource.
    """
    effectiveLabels: Optional[Dict[str, str]] = None
    """
    for all of the labels present on the resource.
    """
    forwardingRuleId: Optional[float] = None
    """
    The unique identifier number for the resource. This identifier is defined by the server.
    """
    id: Optional[str] = None
    """
    an identifier for the resource with format projects/{{project}}/regions/{{region}}/forwardingRules/{{name}}
    """
    ipAddress: Optional[str] = None
    """
    IP address for which this forwarding rule accepts traffic. When a client
    sends traffic to this IP address, the forwarding rule directs the traffic
    to the referenced target or backendService.
    While creating a forwarding rule, specifying an IPAddress is
    required under the following circumstances:
    """
    ipCollection: Optional[str] = None
    """
    Resource reference of a PublicDelegatedPrefix. The PDP must be a sub-PDP
    in EXTERNAL_IPV6_FORWARDING_RULE_CREATION mode.
    Use one of the following formats to specify a sub-PDP when creating an
    IPv6 NetLB forwarding rule using BYOIP:
    Full resource URL, as in:
    """
    ipProtocol: Optional[str] = None
    """
    The IP protocol to which this rule applies.
    For protocol forwarding, valid
    options are TCP, UDP, ESP,
    AH, SCTP, ICMP and
    L3_DEFAULT.
    The valid IP protocols are different for different load balancing products
    as described in Load balancing
    features.
    A Forwarding Rule with protocol L3_DEFAULT can attach with target instance or
    backend service with UNSPECIFIED protocol.
    A forwarding rule with "L3_DEFAULT" IPProtocal cannot be attached to a backend service with TCP or UDP.
    Possible values are: TCP, UDP, ESP, AH, SCTP, ICMP, L3_DEFAULT.
    """
    ipVersion: Optional[str] = None
    """
    The IP address version that will be used by this forwarding rule.
    Valid options are IPV4 and IPV6.
    If not set, the IPv4 address will be used by default.
    Possible values are: IPV4, IPV6.
    """
    isMirroringCollector: Optional[bool] = None
    """
    Indicates whether or not this load balancer can be used as a collector for
    packet mirroring. To prevent mirroring loops, instances behind this
    load balancer will not have their traffic mirrored even if a
    PacketMirroring rule applies to them.
    This can only be set to true for load balancers that have their
    loadBalancingScheme set to INTERNAL.
    """
    labelFingerprint: Optional[str] = None
    """
    The fingerprint used for optimistic locking of this resource.  Used
    internally during updates.
    """
    labels: Optional[Dict[str, str]] = None
    """
    Labels to apply to this forwarding rule.  A list of key->value pairs.
    """
    loadBalancingScheme: Optional[str] = None
    """
    Specifies the forwarding rule type.
    Note that an empty string value ("") is also supported for some use
    cases, for example PSC (private service connection) regional forwarding
    rules.
    For more information about forwarding rules, refer to
    Forwarding rule concepts.
    Default value is EXTERNAL.
    Possible values are: EXTERNAL, EXTERNAL_MANAGED, INTERNAL, INTERNAL_MANAGED.
    """
    network: Optional[str] = None
    """
    This field is not used for external load balancing.
    For Internal TCP/UDP Load Balancing, this field identifies the network that
    the load balanced IP should belong to for this Forwarding Rule.
    If the subnetwork is specified, the network of the subnetwork will be used.
    If neither subnetwork nor this field is specified, the default network will
    be used.
    For Private Service Connect forwarding rules that forward traffic to Google
    APIs, a network must be provided.
    """
    networkTier: Optional[str] = None
    """
    This signifies the networking tier used for configuring
    this load balancer and can only take the following values:
    PREMIUM, STANDARD.
    For regional ForwardingRule, the valid values are PREMIUM and
    STANDARD. For GlobalForwardingRule, the valid value is
    PREMIUM.
    If this field is not specified, it is assumed to be PREMIUM.
    If IPAddress is specified, this value must be equal to the
    networkTier of the Address.
    Possible values are: PREMIUM, STANDARD.
    """
    noAutomateDnsZone: Optional[bool] = None
    """
    This is used in PSC consumer ForwardingRule to control whether it should try to auto-generate a DNS zone or not. Non-PSC forwarding rules do not use this field.
    """
    portRange: Optional[str] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The portRange field has the following limitations:
    """
    ports: Optional[List[str]] = None
    """
    The ports, portRange, and allPorts fields are mutually exclusive.
    Only packets addressed to ports in the specified range will be forwarded
    to the backends configured with this forwarding rule.
    The ports field has the following limitations:
    """
    project: Optional[str] = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    pscConnectionId: Optional[str] = None
    """
    The PSC connection id of the PSC Forwarding Rule.
    """
    pscConnectionStatus: Optional[str] = None
    """
    The PSC connection status of the PSC Forwarding Rule. Possible values: STATUS_UNSPECIFIED, PENDING, ACCEPTED, REJECTED, CLOSED
    """
    recreateClosedPsc: Optional[bool] = None
    """
    this is used in psc consumer forwardingrule to make provider recreate the forwardingrule when the status is closed
    """
    region: Optional[str] = None
    """
    A reference to the region where the regional forwarding rule resides.
    This field is not applicable to global forwarding rules.
    """
    selfLink: Optional[str] = None
    """
    The URI of the created resource.
    """
    serviceDirectoryRegistrations: Optional[ServiceDirectoryRegistrations] = None
    """
    Service Directory resources to register this forwarding rule with.
    Currently, only supports a single Service Directory resource.
    Structure is documented below.
    """
    serviceLabel: Optional[str] = None
    """
    An optional prefix to the service name for this Forwarding Rule.
    If specified, will be the first label of the fully qualified service
    name.
    The label must be 1-63 characters long, and comply with RFC1035.
    Specifically, the label must be 1-63 characters long and match the
    regular expression [a-z]([-a-z0-9]*[a-z0-9])? which means the first
    character must be a lowercase letter, and all following characters
    must be a dash, lowercase letter, or digit, except the last
    character, which cannot be a dash.
    This field is only used for INTERNAL load balancing.
    """
    serviceName: Optional[str] = None
    """
    The internal fully qualified service name for this Forwarding Rule.
    This field is only used for INTERNAL load balancing.
    """
    sourceIpRanges: Optional[List[str]] = None
    """
    If not empty, this Forwarding Rule will only forward the traffic when the source IP address matches one of the IP addresses or CIDR ranges set here. Note that a Forwarding Rule can only have up to 64 source IP ranges, and this field can only be used with a regional Forwarding Rule whose scheme is EXTERNAL. Each sourceIpRange entry should be either an IP address (for example, 1.2.3.4) or a CIDR range (for example, 1.2.3.0/24).
    """
    subnetwork: Optional[str] = None
    """
    This field identifies the subnetwork that the load balanced IP should
    belong to for this Forwarding Rule, used in internal load balancing and
    network load balancing with IPv6.
    If the network specified is in auto subnet mode, this field is optional.
    However, a subnetwork must be specified if the network is in custom subnet
    mode or when creating external forwarding rule with IPv6.
    """
    target: Optional[str] = None
    """
    is set to targetGrpcProxy and
    validateForProxyless is set to true, the
    IPAddress should be set to 0.0.0.0.
    """
    terraformLabels: Optional[Dict[str, str]] = None
    """
    The combination of labels configured directly on the resource
    and default labels configured on the provider.
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: Optional[str] = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: Optional[AtProvider] = None
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class ForwardingRule(BaseModel):
    apiVersion: Optional[Literal['compute.gcp.upbound.io/v1beta2']] = (
        'compute.gcp.upbound.io/v1beta2'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['ForwardingRule']] = 'ForwardingRule'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    ForwardingRuleSpec defines the desired state of ForwardingRule
    """
    status: Optional[Status] = None
    """
    ForwardingRuleStatus defines the observed state of ForwardingRule.
    """


class ForwardingRuleList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[ForwardingRule]
    """
    List of forwardingrules. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """