# generated by datamodel-codegen:
#   filename:  workdir/iam_aws_upbound_io_v1beta1_accountpasswordpolicy.yaml

from __future__ import annotations

from datetime import datetime
from typing import List, Literal, Optional

from pydantic import BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class ForProvider(BaseModel):
    allowUsersToChangePassword: Optional[bool] = None
    """
    Whether to allow users to change their own password
    """
    hardExpiry: Optional[bool] = None
    """
    Whether users are prevented from setting a new password after their password has expired (i.e., require administrator reset)
    """
    maxPasswordAge: Optional[float] = None
    """
    The number of days that an user password is valid.
    """
    minimumPasswordLength: Optional[float] = None
    """
    Minimum length to require for user passwords.
    """
    passwordReusePrevention: Optional[float] = None
    """
    The number of previous passwords that users are prevented from reusing.
    """
    requireLowercaseCharacters: Optional[bool] = None
    """
    Whether to require lowercase characters for user passwords.
    """
    requireNumbers: Optional[bool] = None
    """
    Whether to require numbers for user passwords.
    """
    requireSymbols: Optional[bool] = None
    """
    Whether to require symbols for user passwords.
    """
    requireUppercaseCharacters: Optional[bool] = None
    """
    Whether to require uppercase characters for user passwords.
    """


class InitProvider(BaseModel):
    allowUsersToChangePassword: Optional[bool] = None
    """
    Whether to allow users to change their own password
    """
    hardExpiry: Optional[bool] = None
    """
    Whether users are prevented from setting a new password after their password has expired (i.e., require administrator reset)
    """
    maxPasswordAge: Optional[float] = None
    """
    The number of days that an user password is valid.
    """
    minimumPasswordLength: Optional[float] = None
    """
    Minimum length to require for user passwords.
    """
    passwordReusePrevention: Optional[float] = None
    """
    The number of previous passwords that users are prevented from reusing.
    """
    requireLowercaseCharacters: Optional[bool] = None
    """
    Whether to require lowercase characters for user passwords.
    """
    requireNumbers: Optional[bool] = None
    """
    Whether to require numbers for user passwords.
    """
    requireSymbols: Optional[bool] = None
    """
    Whether to require symbols for user passwords.
    """
    requireUppercaseCharacters: Optional[bool] = None
    """
    Whether to require uppercase characters for user passwords.
    """


class Policy(BaseModel):
    resolution: Optional[Literal['Required', 'Optional']] = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Optional[Literal['Always', 'IfNotPresent']] = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Optional[Policy] = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Optional[Literal['Orphan', 'Delete']] = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: Optional[InitProvider] = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: Optional[
        List[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
    ] = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: Optional[ProviderConfigRef] = Field(
        default_factory=lambda: ProviderConfigRef.model_validate({'name': 'default'})
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: Optional[WriteConnectionSecretToRef] = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    allowUsersToChangePassword: Optional[bool] = None
    """
    Whether to allow users to change their own password
    """
    expirePasswords: Optional[bool] = None
    """
    Indicates whether passwords in the account expire. Returns true if max_password_age contains a value greater than 0. Returns false if it is 0 or not present.
    """
    hardExpiry: Optional[bool] = None
    """
    Whether users are prevented from setting a new password after their password has expired (i.e., require administrator reset)
    """
    id: Optional[str] = None
    maxPasswordAge: Optional[float] = None
    """
    The number of days that an user password is valid.
    """
    minimumPasswordLength: Optional[float] = None
    """
    Minimum length to require for user passwords.
    """
    passwordReusePrevention: Optional[float] = None
    """
    The number of previous passwords that users are prevented from reusing.
    """
    requireLowercaseCharacters: Optional[bool] = None
    """
    Whether to require lowercase characters for user passwords.
    """
    requireNumbers: Optional[bool] = None
    """
    Whether to require numbers for user passwords.
    """
    requireSymbols: Optional[bool] = None
    """
    Whether to require symbols for user passwords.
    """
    requireUppercaseCharacters: Optional[bool] = None
    """
    Whether to require uppercase characters for user passwords.
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: Optional[str] = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: Optional[AtProvider] = None
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class AccountPasswordPolicy(BaseModel):
    apiVersion: Optional[Literal['iam.aws.upbound.io/v1beta1']] = (
        'iam.aws.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['AccountPasswordPolicy']] = 'AccountPasswordPolicy'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    AccountPasswordPolicySpec defines the desired state of AccountPasswordPolicy
    """
    status: Optional[Status] = None
    """
    AccountPasswordPolicyStatus defines the observed state of AccountPasswordPolicy.
    """


class AccountPasswordPolicyList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[AccountPasswordPolicy]
    """
    List of accountpasswordpolicies. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """