apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: eksclusters.infrastructure.modelplane.ai
spec:
  compositeTypeRef:
    apiVersion: infrastructure.modelplane.ai/v1alpha1
    kind: EKSCluster
  mode: Pipeline
  pipeline:
  - functionRef:
      name: modelplane-modelplanecompose-eks-cluster
    step: compose-eks-cluster
  - functionRef:
      name: modelplane-modelplanecompose-usages
    step: compose-usages
