apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kservebackends.infrastructure.modelplane.ai
spec:
  compositeTypeRef:
    apiVersion: infrastructure.modelplane.ai/v1alpha1
    kind: KServeBackend
  mode: Pipeline
  pipeline:
  - functionRef:
      name: negzupboundio-modelplane-infracompose-kserve-backend
    step: compose-kserve-backend
