apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: modelendpoints.modelplane.ai
spec:
  compositeTypeRef:
    apiVersion: modelplane.ai/v1alpha1
    kind: ModelEndpoint
  mode: Pipeline
  pipeline:
  - functionRef:
      name: modelplane-modelplanecompose-model-endpoint
    step: compose-model-endpoint
