apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gkeclusters.infrastructure.modelplane.ai
spec:
  compositeTypeRef:
    apiVersion: infrastructure.modelplane.ai/v1alpha1
    kind: GKECluster
  mode: Pipeline
  pipeline:
  - functionRef:
      name: upbound-modelplane-infracompose-gke-cluster
    step: compose-gke-cluster
