# generated by datamodel-codegen:
#   filename:  workdir/compute_gcp_m_upbound_io_v1beta1_serviceattachment.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class NetworkUrlRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class NetworkUrlSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ConsumerAcceptList(BaseModel):
    connectionLimit: float | None = None
    """
    The number of consumer forwarding rules the consumer project can
    create.
    """
    networkUrl: str | None = None
    """
    The network that is allowed to connect to this service attachment.
    Only one of project_id_or_num and network_url may be set.
    """
    networkUrlRef: NetworkUrlRef | None = None
    """
    Reference to a Network in compute to populate networkUrl.
    """
    networkUrlSelector: NetworkUrlSelector | None = None
    """
    Selector for a Network in compute to populate networkUrl.
    """
    projectIdOrNum: str | None = None
    """
    A project that is allowed to connect to this service attachment.
    Only one of project_id_or_num and network_url may be set.
    """


class NatSubnetsRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class NatSubnetsSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class TargetServiceRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class TargetServiceSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    connectionPreference: str | None = None
    """
    The connection preference to use for this service attachment. Valid
    values include "ACCEPT_AUTOMATIC", "ACCEPT_MANUAL".
    """
    consumerAcceptLists: list[ConsumerAcceptList] | None = None
    """
    An array of projects that are allowed to connect to this service
    attachment.
    Structure is documented below.
    """
    consumerRejectLists: list[str] | None = None
    """
    An array of projects that are not allowed to connect to this service
    attachment.
    """
    description: str | None = None
    """
    An optional description of this resource.
    """
    domainNames: list[str] | None = None
    """
    If specified, the domain name will be used during the integration between
    the PSC connected endpoints and the Cloud DNS. For example, this is a
    valid domain name: "p.mycompany.com.". Current max number of domain names
    supported is 1.
    """
    enableProxyProtocol: bool | None = None
    """
    If true, enable the proxy protocol which is for supplying client TCP/IP
    address data in TCP connections that traverse proxies on their way to
    destination servers.
    """
    natSubnets: list[str] | None = None
    """
    An array of subnets that is provided for NAT in this service attachment.
    """
    natSubnetsRefs: list[NatSubnetsRef] | None = None
    """
    References to Subnetwork in compute to populate natSubnets.
    """
    natSubnetsSelector: NatSubnetsSelector | None = None
    """
    Selector for a list of Subnetwork in compute to populate natSubnets.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    propagatedConnectionLimit: float | None = None
    """
    The number of consumer spokes that connected Private Service Connect endpoints can be propagated to through Network Connectivity Center.
    This limit lets the service producer limit how many propagated Private Service Connect connections can be established to this service attachment from a single consumer.
    If the connection preference of the service attachment is ACCEPT_MANUAL, the limit applies to each project or network that is listed in the consumer accept list.
    If the connection preference of the service attachment is ACCEPT_AUTOMATIC, the limit applies to each project that contains a connected endpoint.
    If unspecified, the default propagated connection limit is 250. To explicitly send a zero value, set send_propagated_connection_limit_if_zero = true.
    """
    reconcileConnections: bool | None = None
    """
    This flag determines whether a consumer accept/reject list change can reconcile the statuses of existing ACCEPTED or REJECTED PSC endpoints.
    If false, connection policy update will only affect existing PENDING PSC endpoints. Existing ACCEPTED/REJECTED endpoints will remain untouched regardless how the connection policy is modified .
    If true, update will affect both PENDING and ACCEPTED/REJECTED PSC endpoints. For example, an ACCEPTED PSC endpoint will be moved to REJECTED if its project is added to the reject list.
    """
    region: str
    """
    URL of the region where the resource resides.
    """
    sendPropagatedConnectionLimitIfZero: bool | None = None
    """
    Controls the behavior of propagated_connection_limit.
    When false, setting propagated_connection_limit to zero causes the provider to use to the API's default value.
    When true, the provider will set propagated_connection_limit to zero.
    Defaults to false.
    """
    targetService: str | None = None
    """
    The URL of a service serving the endpoint identified by this service attachment.
    """
    targetServiceRef: TargetServiceRef | None = None
    """
    Reference to a ForwardingRule in compute to populate targetService.
    """
    targetServiceSelector: TargetServiceSelector | None = None
    """
    Selector for a ForwardingRule in compute to populate targetService.
    """


class InitProvider(BaseModel):
    connectionPreference: str | None = None
    """
    The connection preference to use for this service attachment. Valid
    values include "ACCEPT_AUTOMATIC", "ACCEPT_MANUAL".
    """
    consumerAcceptLists: list[ConsumerAcceptList] | None = None
    """
    An array of projects that are allowed to connect to this service
    attachment.
    Structure is documented below.
    """
    consumerRejectLists: list[str] | None = None
    """
    An array of projects that are not allowed to connect to this service
    attachment.
    """
    description: str | None = None
    """
    An optional description of this resource.
    """
    domainNames: list[str] | None = None
    """
    If specified, the domain name will be used during the integration between
    the PSC connected endpoints and the Cloud DNS. For example, this is a
    valid domain name: "p.mycompany.com.". Current max number of domain names
    supported is 1.
    """
    enableProxyProtocol: bool | None = None
    """
    If true, enable the proxy protocol which is for supplying client TCP/IP
    address data in TCP connections that traverse proxies on their way to
    destination servers.
    """
    natSubnets: list[str] | None = None
    """
    An array of subnets that is provided for NAT in this service attachment.
    """
    natSubnetsRefs: list[NatSubnetsRef] | None = None
    """
    References to Subnetwork in compute to populate natSubnets.
    """
    natSubnetsSelector: NatSubnetsSelector | None = None
    """
    Selector for a list of Subnetwork in compute to populate natSubnets.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    propagatedConnectionLimit: float | None = None
    """
    The number of consumer spokes that connected Private Service Connect endpoints can be propagated to through Network Connectivity Center.
    This limit lets the service producer limit how many propagated Private Service Connect connections can be established to this service attachment from a single consumer.
    If the connection preference of the service attachment is ACCEPT_MANUAL, the limit applies to each project or network that is listed in the consumer accept list.
    If the connection preference of the service attachment is ACCEPT_AUTOMATIC, the limit applies to each project that contains a connected endpoint.
    If unspecified, the default propagated connection limit is 250. To explicitly send a zero value, set send_propagated_connection_limit_if_zero = true.
    """
    reconcileConnections: bool | None = None
    """
    This flag determines whether a consumer accept/reject list change can reconcile the statuses of existing ACCEPTED or REJECTED PSC endpoints.
    If false, connection policy update will only affect existing PENDING PSC endpoints. Existing ACCEPTED/REJECTED endpoints will remain untouched regardless how the connection policy is modified .
    If true, update will affect both PENDING and ACCEPTED/REJECTED PSC endpoints. For example, an ACCEPTED PSC endpoint will be moved to REJECTED if its project is added to the reject list.
    """
    sendPropagatedConnectionLimitIfZero: bool | None = None
    """
    Controls the behavior of propagated_connection_limit.
    When false, setting propagated_connection_limit to zero causes the provider to use to the API's default value.
    When true, the provider will set propagated_connection_limit to zero.
    Defaults to false.
    """
    targetService: str | None = None
    """
    The URL of a service serving the endpoint identified by this service attachment.
    """
    targetServiceRef: TargetServiceRef | None = None
    """
    Reference to a ForwardingRule in compute to populate targetService.
    """
    targetServiceSelector: TargetServiceSelector | None = None
    """
    Selector for a ForwardingRule in compute to populate targetService.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class ConnectedEndpoint(BaseModel):
    consumerNetwork: str | None = None
    """
    (Output)
    The url of the consumer network.
    """
    endpoint: str | None = None
    """
    (Output)
    The URL of the consumer forwarding rule.
    """
    propagatedConnectionCount: float | None = None
    """
    (Output)
    The number of consumer Network Connectivity Center spokes that the connected Private Service Connect endpoint has propagated to.
    """
    pscConnectionId: str | None = None
    """
    (Output)
    The PSC connection id of the connected endpoint.
    """
    status: str | None = None
    """
    (Output)
    The status of the connection from the consumer forwarding rule to
    this service attachment.
    """


class ConsumerAcceptListModel(BaseModel):
    connectionLimit: float | None = None
    """
    The number of consumer forwarding rules the consumer project can
    create.
    """
    networkUrl: str | None = None
    """
    The network that is allowed to connect to this service attachment.
    Only one of project_id_or_num and network_url may be set.
    """
    projectIdOrNum: str | None = None
    """
    A project that is allowed to connect to this service attachment.
    Only one of project_id_or_num and network_url may be set.
    """


class AtProvider(BaseModel):
    connectedEndpoints: list[ConnectedEndpoint] | None = None
    """
    An array of the consumer forwarding rules connected to this service
    attachment.
    Structure is documented below.
    """
    connectionPreference: str | None = None
    """
    The connection preference to use for this service attachment. Valid
    values include "ACCEPT_AUTOMATIC", "ACCEPT_MANUAL".
    """
    consumerAcceptLists: list[ConsumerAcceptListModel] | None = None
    """
    An array of projects that are allowed to connect to this service
    attachment.
    Structure is documented below.
    """
    consumerRejectLists: list[str] | None = None
    """
    An array of projects that are not allowed to connect to this service
    attachment.
    """
    description: str | None = None
    """
    An optional description of this resource.
    """
    domainNames: list[str] | None = None
    """
    If specified, the domain name will be used during the integration between
    the PSC connected endpoints and the Cloud DNS. For example, this is a
    valid domain name: "p.mycompany.com.". Current max number of domain names
    supported is 1.
    """
    enableProxyProtocol: bool | None = None
    """
    If true, enable the proxy protocol which is for supplying client TCP/IP
    address data in TCP connections that traverse proxies on their way to
    destination servers.
    """
    fingerprint: str | None = None
    """
    Fingerprint of this resource. This field is used internally during
    updates of this resource.
    """
    id: str | None = None
    """
    an identifier for the resource with format projects/{{project}}/regions/{{region}}/serviceAttachments/{{name}}
    """
    natSubnets: list[str] | None = None
    """
    An array of subnets that is provided for NAT in this service attachment.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    propagatedConnectionLimit: float | None = None
    """
    The number of consumer spokes that connected Private Service Connect endpoints can be propagated to through Network Connectivity Center.
    This limit lets the service producer limit how many propagated Private Service Connect connections can be established to this service attachment from a single consumer.
    If the connection preference of the service attachment is ACCEPT_MANUAL, the limit applies to each project or network that is listed in the consumer accept list.
    If the connection preference of the service attachment is ACCEPT_AUTOMATIC, the limit applies to each project that contains a connected endpoint.
    If unspecified, the default propagated connection limit is 250. To explicitly send a zero value, set send_propagated_connection_limit_if_zero = true.
    """
    reconcileConnections: bool | None = None
    """
    This flag determines whether a consumer accept/reject list change can reconcile the statuses of existing ACCEPTED or REJECTED PSC endpoints.
    If false, connection policy update will only affect existing PENDING PSC endpoints. Existing ACCEPTED/REJECTED endpoints will remain untouched regardless how the connection policy is modified .
    If true, update will affect both PENDING and ACCEPTED/REJECTED PSC endpoints. For example, an ACCEPTED PSC endpoint will be moved to REJECTED if its project is added to the reject list.
    """
    region: str | None = None
    """
    URL of the region where the resource resides.
    """
    selfLink: str | None = None
    """
    The URI of the created resource.
    """
    sendPropagatedConnectionLimitIfZero: bool | None = None
    """
    Controls the behavior of propagated_connection_limit.
    When false, setting propagated_connection_limit to zero causes the provider to use to the API's default value.
    When true, the provider will set propagated_connection_limit to zero.
    Defaults to false.
    """
    targetService: str | None = None
    """
    The URL of a service serving the endpoint identified by this service attachment.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class ServiceAttachment(BaseModel):
    apiVersion: Literal['compute.gcp.m.upbound.io/v1beta1'] | None = (
        'compute.gcp.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['ServiceAttachment'] | None = 'ServiceAttachment'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    ServiceAttachmentSpec defines the desired state of ServiceAttachment
    """
    status: Status | None = None
    """
    ServiceAttachmentStatus defines the observed state of ServiceAttachment.
    """


class ServiceAttachmentList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[ServiceAttachment]
    """
    List of serviceattachments. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """