# generated by datamodel-codegen:
#   filename:  workdir/compute_nebius_upbound_io_v1beta1_instance.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class IdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class IdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ExistingDisk(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    """
    idRef: IdRef | None = None
    """
    Reference to a Disk in compute to populate id.
    """
    idSelector: IdSelector | None = None
    """
    Selector for a Disk in compute to populate id.
    """


class DiskEncryption(BaseModel):
    type: str | None = None
    """
    (String) :
    :

    #### Supported values

    Possible values:

    - `DISK_ENCRYPTION_UNSPECIFIED` - No encryption is applied unless explicitly specified.
    - `DISK_ENCRYPTION_MANAGED`:
    Enables encryption using the platform's default root key from KMS.
    Available for disks with NETWORK_SSD_NON_REPLICATED and NETWORK_SSD_IO_M3 types only.
    """


class SourceImageFamily(BaseModel):
    imageFamily: str | None = None
    """
    (String)
    """
    parentId: str | None = None
    """
    (String) Identifier of the parent resource to which the resource belongs.
    """


class Spec(BaseModel):
    blockSizeBytes: float | None = None
    """
    (Number) :
    :

    Block size in bytes.
    The block size must be a power of two between 4096 bytes (4 KiB) and 131072 bytes (128 KiB).
    The default value is 4096 bytes (4 KiB).
    """
    diskEncryption: DiskEncryption | None = None
    """
    (Attributes) Defines how data on the disk is encrypted. By default, no encryption is applied. (see below for nested schema)
    """
    forbidDeletion: bool | None = None
    """
    (Boolean) Prevents deletion whilst set
    Prevents deletion whilst set
    """
    sizeBytes: float | None = None
    """
    (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
    *Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.*
    """
    sizeGibibytes: float | None = None
    """
    (Number) Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.
    *Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.*
    """
    sizeKibibytes: float | None = None
    """
    (Number) Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.
    *Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.*
    """
    sizeMebibytes: float | None = None
    """
    (Number) Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.
    *Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.*
    """
    sourceImageFamily: SourceImageFamily | None = None
    """
    (Attributes) Cannot be set alongside source_image_id. (see below for nested schema)
    """
    sourceImageId: str | None = None
    """
    (String) Cannot be set alongside source_image_family.
    *Cannot be set alongside source_image_family.*
    """
    type: str | None = None
    """
    (String) :
    :

    The type of disk defines the performance and reliability characteristics of the block device.
    For details, see https://docs.nebius.com/compute/storage/types#disks-types

    #### Supported values

    the list of available types will be clarified later, it is not final version
    Possible values:

    - `UNSPECIFIED`
    - `NETWORK_SSD`
    - `NETWORK_HDD`
    - `NETWORK_SSD_NON_REPLICATED`
    - `NETWORK_SSD_IO_M3`
    """


class ManagedDisk(BaseModel):
    labels: dict[str, str] | None = None
    """
    (Map of String) Labels associated with the resource.
    Labels associated with disk resource.
    """
    name: str | None = None
    """
    (String) Human readable name for the resource.
    :

    Name of a dependent disk.
    Use it to convert an ExistingDisk to a dependent disk.
    Changing the name will replace the disk and cause data loss.
    """
    spec: Spec | None = None
    """
    (Attributes) Specification of a dependent disk to be created. (see below for nested schema)
    """


class BootDisk(BaseModel):
    attachMode: str | None = None
    """
    (String) :
    :

    #### Supported values

    Possible values:

    - `UNSPECIFIED`
    - `READ_ONLY`
    - `READ_WRITE`
    """
    deviceId: str | None = None
    """
    defined identifier, allowing to use '/dev/disk/by-id/virtio-{device_id}' as a device path in mount command.
    Specifies the user-defined identifier, allowing to use '/dev/disk/by-id/virtio-{device_id}' as a device path in mount command.
    """
    existingDisk: ExistingDisk | None = None
    """
    (Attributes) :
    """
    managedDisk: ManagedDisk | None = None
    """
    (Attributes) :
    """


class CloudInitUserDataSecretRef(BaseModel):
    key: str
    """
    The key to select.
    """
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class ExistingFilesystem(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    """
    idRef: IdRef | None = None
    """
    Reference to a Filesystem in compute to populate id.
    """
    idSelector: IdSelector | None = None
    """
    Selector for a Filesystem in compute to populate id.
    """


class Filesystem(BaseModel):
    attachMode: str | None = None
    """
    (String) :
    :

    #### Supported values

    Possible values:

    - `UNSPECIFIED`
    - `READ_ONLY`
    - `READ_WRITE`
    """
    existingFilesystem: ExistingFilesystem | None = None
    """
    (Attributes) (see below for nested schema)
    """
    mountTag: str | None = None
    """
    defined identifier, allowing to use it as a device in mount command.
    Specifies the user-defined identifier, allowing to use it as a device in mount command.
    """


class GpuCluster(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    :

    If you want to interconnect several instances in a GPU cluster via NVIDIA InfiniBand,
    set the ID of an existing GPU cluster.
    You can only add the VM to the cluster when creating the VM.
    For details, see https://docs.nebius.com/compute/clusters/gpu
    """
    idRef: IdRef | None = None
    """
    Reference to a GpuCluster in compute to populate id.
    """
    idSelector: IdSelector | None = None
    """
    Selector for a GpuCluster in compute to populate id.
    """


class PassthroughGroup(BaseModel):
    requested: bool | None = None
    """
    (Boolean) :
    :

    Passthrough local disks from the underlying host.

    Devices are expected to appear in the guest as NVMe devices (nvme0, nvme1, ...),
    but the exact number depends on the preset.
    Enabled only when this field is explicitly set.
    """


class LocalDisks(BaseModel):
    passthroughGroup: PassthroughGroup | None = None
    """
    (Attributes) :
    """


class Alias(BaseModel):
    allocationId: str | None = None
    """
    (String) Allocation identifier if it was created before.
    ID of allocation
    """


class IpAddress(BaseModel):
    allocationId: str | None = None
    """
    (String) Allocation identifier if it was created before.
    Allocation identifier if it was created before.
    """


class PublicIpAddress(BaseModel):
    allocationId: str | None = None
    """
    (String) Allocation identifier if it was created before.
    Allocation identifier if it was created before.
    """
    static: bool | None = None
    """
    (Boolean) :
    :

    If false - Allocation will be created/deleted during NetworkInterface.Allocate/NetworkInterface.Deallocate
    If true  - Allocation will be created/deleted during NetworkInterface.Create/NetworkInterface.Delete
    False by default
    """


class SecurityGroup(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    Security group identifier
    """
    idRef: IdRef | None = None
    """
    Reference to a SecurityGroup in vpc to populate id.
    """
    idSelector: IdSelector | None = None
    """
    Selector for a SecurityGroup in vpc to populate id.
    """


class SubnetIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SubnetIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class NetworkInterface(BaseModel):
    aliases: list[Alias] | None = None
    """
    (Attributes List) Assign ranges of IP addresses as aliases (see below for nested schema)
    """
    ipAddress: IpAddress | None = None
    """
    (Attributes) :
    """
    name: str | None = None
    """
    (String) Human readable name for the resource.
    :

    Interface name
    Value of this field configures the name of the network interface inside VM's OS.
    Longer values will persist in the specification but will be truncated to 15 symbols before being passed to VM configuration.
    """
    publicIpAddress: PublicIpAddress | None = None
    """
    (Attributes) :
    """
    securityGroups: list[SecurityGroup] | None = None
    """
    (Attributes List) :
    """
    subnetId: str | None = None
    """
    (String) Subnet ID
    Subnet ID
    """
    subnetIdRef: SubnetIdRef | None = None
    """
    Reference to a Subnet in vpc to populate subnetId.
    """
    subnetIdSelector: SubnetIdSelector | None = None
    """
    Selector for a Subnet in vpc to populate subnetId.
    """


class Preemptible(BaseModel):
    onPreemption: str | None = None
    """
    (String) :
    :

    Specifies what happens when the VM is preempted. The only supported value is STOP:
    Compute stops the VM without deleting or restarting it.

    #### Supported values

    Possible values:

    - `UNSPECIFIED`
    - `STOP`
    """
    priority: float | None = None
    """
    (Number, Deprecated)
    """


class ReservationPolicy(BaseModel):
    policy: str | None = None
    """
    (String) :
    :

    #### Supported values

    Possible values:

    - `AUTO`:
    1) Will try to launch instance in any reservation_ids if provided.
    2) Will try to launch instance in any of the available capacity block.
    3) Will try to launch instance in PAYG if 1 & 2 are not satisfied.

    - `FORBID`:
    The instance is launched only using on-demand (PAYG) capacity.
    No attempt is made to find or use a Capacity Block.
    It's an error to provide reservation_ids with policy = FORBID

    - `STRICT`:
    1) Will try to launch the instance in Capacity Blocks from reservation_ids if provided.
    2) If reservation_ids are not provided will try to launch instance in suitable & available Capacity Block.
    3) Fail otherwise.
    """
    reservationIds: list[str] | None = None
    """
    (List of String) Capacity block groups, order matters
    Capacity block groups, order matters
    """


class Resources(BaseModel):
    platform: str | None = None
    """
    (String)
    """
    preset: str | None = None
    """
    (String)
    """


class SecondaryDisk(BaseModel):
    attachMode: str | None = None
    """
    (String) :
    :

    #### Supported values

    Possible values:

    - `UNSPECIFIED`
    - `READ_ONLY`
    - `READ_WRITE`
    """
    deviceId: str | None = None
    """
    defined identifier, allowing to use '/dev/disk/by-id/virtio-{device_id}' as a device path in mount command.
    Specifies the user-defined identifier, allowing to use '/dev/disk/by-id/virtio-{device_id}' as a device path in mount command.
    """
    existingDisk: ExistingDisk | None = None
    """
    (Attributes) :
    """
    managedDisk: ManagedDisk | None = None
    """
    (Attributes) :
    """


class ServiceAccountIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ServiceAccountIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    bootDisk: BootDisk | None = None
    """
    (Attributes) Specified boot disk attached to the instance. (see below for nested schema)
    """
    cloudInitUserDataSecretRef: CloudInitUserDataSecretRef | None = None
    """
    (String, Sensitive) :
    :

    Data in cloud-init format for customizing instance initialization.
    For details, see https://docs.nebius.com/compute/virtual-machines/manage#user-data
    """
    filesystems: list[Filesystem] | None = None
    """
    (Attributes List) List of Shared Filesystems attached to the instance. (see below for nested schema)
    """
    gpuCluster: GpuCluster | None = None
    """
    (Attributes) :
    """
    hostname: str | None = None
    """
    (String) :
    :

    Instance's hostname. Used to generate default DNS record in format `<hostname>.<network_id>.compute.internal.`
    or `<instance_id>.<network_id>.compute.internal.` if hostname is not specified.
    """
    labels: dict[str, str] | None = None
    """
    (Map of String) Labels associated with the resource.
    Labels associated with the resource.
    """
    localDisks: LocalDisks | None = None
    """
    (Attributes) :
    """
    metadata: dict[str, Any] | None = None
    """
    (Attributes) :
    """
    name: str | None = None
    """
    (String) Human readable name for the resource.
    Human readable name for the resource.
    """
    networkInterfaces: list[NetworkInterface] | None = None
    """
    (Attributes List) :
    """
    nvlInstanceGroupId: str | None = None
    """
    (String) NVLink Instance Group ID associated with the VM
    NVLink Instance Group ID associated with the VM
    """
    parentId: str | None = None
    """
    (String) Identifier of the parent resource to which the resource belongs.
    Identifier of the parent resource to which the resource belongs.
    """
    preemptible: Preemptible | None = None
    """
    (Attributes) :
    """
    recoveryPolicy: str | None = None
    """
    (String) :
    :

    Recovery policy defines how the instance will be treated in case of a failure.
    Common source of failure is a host failure, but it can be any other failure.
    Instance undergoing a guest shutdown (poweroff, etc.) will be subject to recovery policy, meaning that it could
    be restarted and billed accordingly. Stop instance via API or UI to stop it to avoid recovering.
    - If set to RECOVER, instance will be restarted, if possible. It could be restarted on the same host or on another host.
    - If set to FAIL, instance will be stopped and not restarted.

    #### Supported values

    Possible values:

    - `RECOVER`
    - `FAIL`
    """
    reservationPolicy: ReservationPolicy | None = None
    """
    (Attributes) (see below for nested schema)
    """
    resources: Resources | None = None
    """
    (Attributes) :
    """
    secondaryDisks: list[SecondaryDisk] | None = None
    """
    (Attributes List) List of additional data disks attached to the instance beyond the boot disk. (see below for nested schema)
    """
    serviceAccountId: str | None = None
    """
    (String) :
    :

    Unique identifier of the service account associated with this instance.
    For details, see https://docs.nebius.com/iam/service-accounts/manage
    """
    serviceAccountIdRef: ServiceAccountIdRef | None = None
    """
    Reference to a ServiceAccount in iam to populate serviceAccountId.
    """
    serviceAccountIdSelector: ServiceAccountIdSelector | None = None
    """
    Selector for a ServiceAccount in iam to populate serviceAccountId.
    """
    stopped: bool | None = None
    """
    (Boolean) Indicates whether the instance should be stopped.
    Indicates whether the instance should be stopped.
    """


class InitProvider(BaseModel):
    bootDisk: BootDisk | None = None
    """
    (Attributes) Specified boot disk attached to the instance. (see below for nested schema)
    """
    cloudInitUserDataSecretRef: CloudInitUserDataSecretRef | None = None
    """
    (String, Sensitive) :
    :

    Data in cloud-init format for customizing instance initialization.
    For details, see https://docs.nebius.com/compute/virtual-machines/manage#user-data
    """
    filesystems: list[Filesystem] | None = None
    """
    (Attributes List) List of Shared Filesystems attached to the instance. (see below for nested schema)
    """
    gpuCluster: GpuCluster | None = None
    """
    (Attributes) :
    """
    hostname: str | None = None
    """
    (String) :
    :

    Instance's hostname. Used to generate default DNS record in format `<hostname>.<network_id>.compute.internal.`
    or `<instance_id>.<network_id>.compute.internal.` if hostname is not specified.
    """
    labels: dict[str, str] | None = None
    """
    (Map of String) Labels associated with the resource.
    Labels associated with the resource.
    """
    localDisks: LocalDisks | None = None
    """
    (Attributes) :
    """
    metadata: dict[str, Any] | None = None
    """
    (Attributes) :
    """
    name: str | None = None
    """
    (String) Human readable name for the resource.
    Human readable name for the resource.
    """
    networkInterfaces: list[NetworkInterface] | None = None
    """
    (Attributes List) :
    """
    nvlInstanceGroupId: str | None = None
    """
    (String) NVLink Instance Group ID associated with the VM
    NVLink Instance Group ID associated with the VM
    """
    parentId: str | None = None
    """
    (String) Identifier of the parent resource to which the resource belongs.
    Identifier of the parent resource to which the resource belongs.
    """
    preemptible: Preemptible | None = None
    """
    (Attributes) :
    """
    recoveryPolicy: str | None = None
    """
    (String) :
    :

    Recovery policy defines how the instance will be treated in case of a failure.
    Common source of failure is a host failure, but it can be any other failure.
    Instance undergoing a guest shutdown (poweroff, etc.) will be subject to recovery policy, meaning that it could
    be restarted and billed accordingly. Stop instance via API or UI to stop it to avoid recovering.
    - If set to RECOVER, instance will be restarted, if possible. It could be restarted on the same host or on another host.
    - If set to FAIL, instance will be stopped and not restarted.

    #### Supported values

    Possible values:

    - `RECOVER`
    - `FAIL`
    """
    reservationPolicy: ReservationPolicy | None = None
    """
    (Attributes) (see below for nested schema)
    """
    resources: Resources | None = None
    """
    (Attributes) :
    """
    secondaryDisks: list[SecondaryDisk] | None = None
    """
    (Attributes List) List of additional data disks attached to the instance beyond the boot disk. (see below for nested schema)
    """
    serviceAccountId: str | None = None
    """
    (String) :
    :

    Unique identifier of the service account associated with this instance.
    For details, see https://docs.nebius.com/iam/service-accounts/manage
    """
    serviceAccountIdRef: ServiceAccountIdRef | None = None
    """
    Reference to a ServiceAccount in iam to populate serviceAccountId.
    """
    serviceAccountIdSelector: ServiceAccountIdSelector | None = None
    """
    Selector for a ServiceAccount in iam to populate serviceAccountId.
    """
    stopped: bool | None = None
    """
    (Boolean) Indicates whether the instance should be stopped.
    Indicates whether the instance should be stopped.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class SpecModel(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class ExistingDiskModel(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    """


class SpecModel1(BaseModel):
    blockSizeBytes: float | None = None
    """
    (Number) :
    :

    Block size in bytes.
    The block size must be a power of two between 4096 bytes (4 KiB) and 131072 bytes (128 KiB).
    The default value is 4096 bytes (4 KiB).
    """
    diskEncryption: DiskEncryption | None = None
    """
    (Attributes) Defines how data on the disk is encrypted. By default, no encryption is applied. (see below for nested schema)
    """
    forbidDeletion: bool | None = None
    """
    (Boolean) Prevents deletion whilst set
    Prevents deletion whilst set
    """
    sizeBytes: float | None = None
    """
    (Number) Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.
    *Cannot be set alongside size_kibibytes, size_mebibytes or size_gibibytes.*
    """
    sizeGibibytes: float | None = None
    """
    (Number) Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.
    *Cannot be set alongside size_bytes, size_kibibytes or size_mebibytes.*
    """
    sizeKibibytes: float | None = None
    """
    (Number) Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.
    *Cannot be set alongside size_bytes, size_mebibytes or size_gibibytes.*
    """
    sizeMebibytes: float | None = None
    """
    (Number) Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.
    *Cannot be set alongside size_bytes, size_kibibytes or size_gibibytes.*
    """
    sourceImageFamily: SourceImageFamily | None = None
    """
    (Attributes) Cannot be set alongside source_image_id. (see below for nested schema)
    """
    sourceImageId: str | None = None
    """
    (String) Cannot be set alongside source_image_family.
    *Cannot be set alongside source_image_family.*
    """
    type: str | None = None
    """
    (String) :
    :

    The type of disk defines the performance and reliability characteristics of the block device.
    For details, see https://docs.nebius.com/compute/storage/types#disks-types

    #### Supported values

    the list of available types will be clarified later, it is not final version
    Possible values:

    - `UNSPECIFIED`
    - `NETWORK_SSD`
    - `NETWORK_HDD`
    - `NETWORK_SSD_NON_REPLICATED`
    - `NETWORK_SSD_IO_M3`
    """


class ExistingFilesystemModel(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    """


class GpuClusterModel(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    :

    If you want to interconnect several instances in a GPU cluster via NVIDIA InfiniBand,
    set the ID of an existing GPU cluster.
    You can only add the VM to the cluster when creating the VM.
    For details, see https://docs.nebius.com/compute/clusters/gpu
    """


class SecurityGroupModel(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    Security group identifier
    """


class NetworkInterfaceModel(BaseModel):
    aliases: list[Alias] | None = None
    """
    (Attributes List) Assign ranges of IP addresses as aliases (see below for nested schema)
    """
    ipAddress: IpAddress | None = None
    """
    (Attributes) :
    """
    name: str | None = None
    """
    (String) Human readable name for the resource.
    :

    Interface name
    Value of this field configures the name of the network interface inside VM's OS.
    Longer values will persist in the specification but will be truncated to 15 symbols before being passed to VM configuration.
    """
    publicIpAddress: PublicIpAddress | None = None
    """
    (Attributes) :
    """
    securityGroups: list[SecurityGroupModel] | None = None
    """
    (Attributes List) :
    """
    subnetId: str | None = None
    """
    (String) Subnet ID
    Subnet ID
    """


class DiskAttachment(BaseModel):
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    :

    Disk ID.
    - For ExistingDisk, this is the referenced disk ID.
    - For ManagedDisk, may be empty while the attachment intent is still pending.
    """
    isManaged: bool | None = None
    """
    (Boolean) :
    :

    Indicates whether this attachment is managed by the instance lifecycle.
    If true, the disk is expected to be deleted when the instance is deleted.
    If false, the disk is preserved and only detached on instance deletion.
    """
    name: str | None = None
    """
    (String) Human readable name for the resource.
    :

    Disk name used to match this status entry with the desired attachment
    from the instance specification.

    Consistency:
    - For ManagedDisk, this value is derived from the instance spec (ManagedDisk.name).
    - For ExistingDisk, this value is derived from the disk resource name and may lag behind
    in case of renaming. It is updated asynchronously and is eventually consistent.
    """


class InfinibandTopologyPath(BaseModel):
    path: list[str] | None = None
    """
    (List of String)
    """


class Aliases(BaseModel):
    cidrs: list[str] | None = None
    """
    (List of String)
    """


class IpAddressModel(BaseModel):
    address: str | None = None
    """
    (String) Effective private IPv4 address assigned to the interface.
    Effective private IPv4 address assigned to the interface.
    """
    allocationId: str | None = None
    """
    (String) Allocation identifier if it was created before.
    Allocation identifier.
    """


class PublicIpAddressModel(BaseModel):
    address: str | None = None
    """
    (String) Effective private IPv4 address assigned to the interface.
    Effective public IPv4 address assigned to the interface.
    """
    allocationId: str | None = None
    """
    (String) Allocation identifier if it was created before.
    Allocation identifier.
    """
    static: bool | None = None
    """
    (Boolean) :
    :

    If false - Allocation will be created/deleted during NetworkInterface.Allocate/NetworkInterface.Deallocate
    If true  - Allocation will be created/deleted during NetworkInterface.Create/NetworkInterface.Delete
    False by default
    """


class NetworkInterfaceModel1(BaseModel):
    aliases: Aliases | None = None
    """
    (Attributes List) Assign ranges of IP addresses as aliases (see below for nested schema)
    """
    fqdn: str | None = None
    """
    (String) FQDN of the interface
    FQDN of the interface
    """
    index: float | None = None
    """
    (Number) The index of the network interface
    The index of the network interface
    """
    ipAddress: IpAddressModel | None = None
    """
    (Attributes) :
    """
    macAddress: str | None = None
    """
    (String) MAC address
    MAC address
    """
    name: str | None = None
    """
    (String) Human readable name for the resource.
    :

    Name for interface.
    Unique within instance's network interfaces
    """
    publicIpAddress: PublicIpAddressModel | None = None
    """
    (Attributes) :
    """


class Status(BaseModel):
    diskAttachments: list[DiskAttachment] | None = None
    """
    .
    """
    infinibandTopologyPath: InfinibandTopologyPath | None = None
    """
    (Attributes) (see below for nested schema)
    """
    maintenanceEventId: str | None = None
    """
    (String)
    """
    networkInterfaces: list[NetworkInterfaceModel1] | None = None
    """
    (Attributes List) :
    """
    reconciling: bool | None = None
    """
    (Boolean) Indicates whether there is an ongoing operation
    Indicates whether there is an ongoing operation
    """
    reservationId: str | None = None
    """
    (String)
    """
    state: str | None = None
    """
    (String) :
    :

    #### Supported values

    Possible values:

    - `UNSPECIFIED`
    - `CREATING`
    - `UPDATING`
    - `STARTING`
    - `RUNNING`
    - `STOPPING`
    - `STOPPED`
    - `DELETING`
    - `ERROR`
    """


class AtProvider(BaseModel):
    bootDisk: BootDisk | None = None
    """
    (Attributes) Specified boot disk attached to the instance. (see below for nested schema)
    """
    createdAt: str | None = None
    """
    (String) :
    :

    Timestamp indicating when the resource was created.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """
    filesystems: list[Filesystem] | None = None
    """
    (Attributes List) List of Shared Filesystems attached to the instance. (see below for nested schema)
    """
    gpuCluster: GpuClusterModel | None = None
    """
    (Attributes) :
    """
    hostname: str | None = None
    """
    (String) :
    :

    Instance's hostname. Used to generate default DNS record in format `<hostname>.<network_id>.compute.internal.`
    or `<instance_id>.<network_id>.compute.internal.` if hostname is not specified.
    """
    id: str | None = None
    """
    (String) Identifier for the resource, unique for its resource type.
    """
    labels: dict[str, str] | None = None
    """
    (Map of String) Labels associated with the resource.
    Labels associated with the resource.
    """
    localDisks: LocalDisks | None = None
    """
    (Attributes) :
    """
    metadata: dict[str, Any] | None = None
    """
    (Attributes) :
    """
    name: str | None = None
    """
    (String) Human readable name for the resource.
    Human readable name for the resource.
    """
    networkInterfaces: list[NetworkInterfaceModel] | None = None
    """
    (Attributes List) :
    """
    nvlInstanceGroupId: str | None = None
    """
    (String) NVLink Instance Group ID associated with the VM
    NVLink Instance Group ID associated with the VM
    """
    parentId: str | None = None
    """
    (String) Identifier of the parent resource to which the resource belongs.
    Identifier of the parent resource to which the resource belongs.
    """
    preemptible: Preemptible | None = None
    """
    (Attributes) :
    """
    recoveryPolicy: str | None = None
    """
    (String) :
    :

    Recovery policy defines how the instance will be treated in case of a failure.
    Common source of failure is a host failure, but it can be any other failure.
    Instance undergoing a guest shutdown (poweroff, etc.) will be subject to recovery policy, meaning that it could
    be restarted and billed accordingly. Stop instance via API or UI to stop it to avoid recovering.
    - If set to RECOVER, instance will be restarted, if possible. It could be restarted on the same host or on another host.
    - If set to FAIL, instance will be stopped and not restarted.

    #### Supported values

    Possible values:

    - `RECOVER`
    - `FAIL`
    """
    reservationPolicy: ReservationPolicy | None = None
    """
    (Attributes) (see below for nested schema)
    """
    resourceVersion: float | None = None
    """
    (Number) :
    :

    Version of the resource for safe concurrent modifications and consistent reads.
    Positive and monotonically increases on each resource spec change (but *not* on each change of the
    resource's container(s) or status).
    Service allows zero value or current.
    """
    resources: Resources | None = None
    """
    (Attributes) :
    """
    secondaryDisks: list[SecondaryDisk] | None = None
    """
    (Attributes List) List of additional data disks attached to the instance beyond the boot disk. (see below for nested schema)
    """
    serviceAccountId: str | None = None
    """
    (String) :
    :

    Unique identifier of the service account associated with this instance.
    For details, see https://docs.nebius.com/iam/service-accounts/manage
    """
    status: Status | None = None
    """
    (Attributes) (see below for nested schema)
    """
    stopped: bool | None = None
    """
    (Boolean) Indicates whether the instance should be stopped.
    Indicates whether the instance should be stopped.
    """
    updatedAt: str | None = None
    """
    (String) :
    :

    Timestamp indicating when the resource was last updated.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class StatusModel(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Instance(BaseModel):
    apiVersion: Literal['compute.nebius.upbound.io/v1beta1'] | None = (
        'compute.nebius.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Instance'] | None = 'Instance'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: SpecModel
    """
    InstanceSpec defines the desired state of Instance
    """
    status: StatusModel | None = None
    """
    InstanceStatus defines the observed state of Instance.
    """


class InstanceList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Instance]
    """
    List of instances. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """