# generated by datamodel-codegen:
#   filename:  workdir/compute_gcp_upbound_io_v1beta2_regionnetworkendpointgroup.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class AppEngine(BaseModel):
    service: str | None = None
    """
    Optional serving service.
    The service name must be 1-63 characters long, and comply with RFC1035.
    Example value: "default", "my-service".
    """
    urlMask: str | None = None
    """
    A template to parse service and version fields from a request URL.
    URL mask allows for routing to multiple App Engine services without
    having to create multiple Network Endpoint Groups and backend services.
    For example, the request URLs "foo1-dot-appname.appspot.com/v1" and
    "foo1-dot-appname.appspot.com/v2" can be backed by the same Serverless NEG with
    URL mask "-dot-appname.appspot.com/". The URL mask will parse
    them to { service = "foo1", version = "v1" } and { service = "foo1", version = "v2" } respectively.
    """
    version: str | None = None
    """
    Optional serving version.
    The version must be 1-63 characters long, and comply with RFC1035.
    Example value: "v1", "v2".
    """


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class FunctionRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class FunctionSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class CloudFunction(BaseModel):
    function: str | None = None
    """
    A user-defined name of the Cloud Function.
    The function name is case-sensitive and must be 1-63 characters long.
    Example value: "func1".
    """
    functionRef: FunctionRef | None = None
    """
    Reference to a Function in cloudfunctions to populate function.
    """
    functionSelector: FunctionSelector | None = None
    """
    Selector for a Function in cloudfunctions to populate function.
    """
    urlMask: str | None = None
    """
    A template to parse function field from a request URL. URL mask allows
    for routing to multiple Cloud Functions without having to create
    multiple Network Endpoint Groups and backend services.
    For example, request URLs "mydomain.com/function1" and "mydomain.com/function2"
    can be backed by the same Serverless NEG with URL mask "/". The URL mask
    will parse them to { function = "function1" } and { function = "function2" } respectively.
    """


class ServiceRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ServiceSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class CloudRun(BaseModel):
    service: str | None = None
    """
    Cloud Run service is the main resource of Cloud Run.
    The service must be 1-63 characters long, and comply with RFC1035.
    Example value: "run-service".
    """
    serviceRef: ServiceRef | None = None
    """
    Reference to a Service in cloudrun to populate service.
    """
    serviceSelector: ServiceSelector | None = None
    """
    Selector for a Service in cloudrun to populate service.
    """
    tag: str | None = None
    """
    Cloud Run tag represents the "named-revision" to provide
    additional fine-grained traffic routing information.
    The tag must be 1-63 characters long, and comply with RFC1035.
    Example value: "revision-0010".
    """
    urlMask: str | None = None
    """
    A template to parse service and tag fields from a request URL.
    URL mask allows for routing to multiple Run services without having
    to create multiple network endpoint groups and backend services.
    For example, request URLs "foo1.domain.com/bar1" and "foo1.domain.com/bar2"
    an be backed by the same Serverless Network Endpoint Group (NEG) with
    URL mask ".domain.com/". The URL mask will parse them to { service="bar1", tag="foo1" }
    and { service="bar2", tag="foo2" } respectively.
    """


class NetworkRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class NetworkSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class PscData(BaseModel):
    producerPort: str | None = None
    """
    The PSC producer port to use when consumer PSC NEG connects to a producer. If
    this flag isn't specified for a PSC NEG with endpoint type
    private-service-connect, then PSC NEG will be connected to a first port in the
    available PSC producer port range.
    """


class PscTargetServiceRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class PscTargetServiceSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class SubnetworkRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SubnetworkSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    appEngine: AppEngine | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    cloudFunction: CloudFunction | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    cloudRun: CloudRun | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    description: str | None = None
    """
    An optional description of this resource. Provide this property when
    you create the resource.
    """
    network: str | None = None
    """
    This field is only used for PSC and INTERNET NEGs.
    The URL of the network to which all network endpoints in the NEG belong. Uses
    "default" project network if unspecified.
    """
    networkEndpointType: str | None = None
    """
    Type of network endpoints in this network endpoint group. Defaults to SERVERLESS.
    Default value is SERVERLESS.
    Possible values are: SERVERLESS, PRIVATE_SERVICE_CONNECT, INTERNET_IP_PORT, INTERNET_FQDN_PORT, GCE_VM_IP_PORTMAP.
    """
    networkRef: NetworkRef | None = None
    """
    Reference to a Network in compute to populate network.
    """
    networkSelector: NetworkSelector | None = None
    """
    Selector for a Network in compute to populate network.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    pscData: PscData | None = None
    """
    This field is only used for PSC NEGs.
    Structure is documented below.
    """
    pscTargetService: str | None = None
    """
    This field is only used for PSC and INTERNET NEGs.
    The target service url used to set up private service connection to
    a Google API or a PSC Producer Service Attachment.
    """
    pscTargetServiceRef: PscTargetServiceRef | None = None
    """
    Reference to a ServiceAttachment in compute to populate pscTargetService.
    """
    pscTargetServiceSelector: PscTargetServiceSelector | None = None
    """
    Selector for a ServiceAttachment in compute to populate pscTargetService.
    """
    region: str
    """
    A reference to the region where the regional NEGs reside.
    """
    subnetwork: str | None = None
    """
    This field is only used for PSC NEGs.
    Optional URL of the subnetwork to which all network endpoints in the NEG belong.
    """
    subnetworkRef: SubnetworkRef | None = None
    """
    Reference to a Subnetwork in compute to populate subnetwork.
    """
    subnetworkSelector: SubnetworkSelector | None = None
    """
    Selector for a Subnetwork in compute to populate subnetwork.
    """


class InitProvider(BaseModel):
    appEngine: AppEngine | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    cloudFunction: CloudFunction | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    cloudRun: CloudRun | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    description: str | None = None
    """
    An optional description of this resource. Provide this property when
    you create the resource.
    """
    network: str | None = None
    """
    This field is only used for PSC and INTERNET NEGs.
    The URL of the network to which all network endpoints in the NEG belong. Uses
    "default" project network if unspecified.
    """
    networkEndpointType: str | None = None
    """
    Type of network endpoints in this network endpoint group. Defaults to SERVERLESS.
    Default value is SERVERLESS.
    Possible values are: SERVERLESS, PRIVATE_SERVICE_CONNECT, INTERNET_IP_PORT, INTERNET_FQDN_PORT, GCE_VM_IP_PORTMAP.
    """
    networkRef: NetworkRef | None = None
    """
    Reference to a Network in compute to populate network.
    """
    networkSelector: NetworkSelector | None = None
    """
    Selector for a Network in compute to populate network.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    pscData: PscData | None = None
    """
    This field is only used for PSC NEGs.
    Structure is documented below.
    """
    pscTargetService: str | None = None
    """
    This field is only used for PSC and INTERNET NEGs.
    The target service url used to set up private service connection to
    a Google API or a PSC Producer Service Attachment.
    """
    pscTargetServiceRef: PscTargetServiceRef | None = None
    """
    Reference to a ServiceAttachment in compute to populate pscTargetService.
    """
    pscTargetServiceSelector: PscTargetServiceSelector | None = None
    """
    Selector for a ServiceAttachment in compute to populate pscTargetService.
    """
    subnetwork: str | None = None
    """
    This field is only used for PSC NEGs.
    Optional URL of the subnetwork to which all network endpoints in the NEG belong.
    """
    subnetworkRef: SubnetworkRef | None = None
    """
    Reference to a Subnetwork in compute to populate subnetwork.
    """
    subnetworkSelector: SubnetworkSelector | None = None
    """
    Selector for a Subnetwork in compute to populate subnetwork.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class CloudFunctionModel(BaseModel):
    function: str | None = None
    """
    A user-defined name of the Cloud Function.
    The function name is case-sensitive and must be 1-63 characters long.
    Example value: "func1".
    """
    urlMask: str | None = None
    """
    A template to parse function field from a request URL. URL mask allows
    for routing to multiple Cloud Functions without having to create
    multiple Network Endpoint Groups and backend services.
    For example, request URLs "mydomain.com/function1" and "mydomain.com/function2"
    can be backed by the same Serverless NEG with URL mask "/". The URL mask
    will parse them to { function = "function1" } and { function = "function2" } respectively.
    """


class CloudRunModel(BaseModel):
    service: str | None = None
    """
    Cloud Run service is the main resource of Cloud Run.
    The service must be 1-63 characters long, and comply with RFC1035.
    Example value: "run-service".
    """
    tag: str | None = None
    """
    Cloud Run tag represents the "named-revision" to provide
    additional fine-grained traffic routing information.
    The tag must be 1-63 characters long, and comply with RFC1035.
    Example value: "revision-0010".
    """
    urlMask: str | None = None
    """
    A template to parse service and tag fields from a request URL.
    URL mask allows for routing to multiple Run services without having
    to create multiple network endpoint groups and backend services.
    For example, request URLs "foo1.domain.com/bar1" and "foo1.domain.com/bar2"
    an be backed by the same Serverless Network Endpoint Group (NEG) with
    URL mask ".domain.com/". The URL mask will parse them to { service="bar1", tag="foo1" }
    and { service="bar2", tag="foo2" } respectively.
    """


class AtProvider(BaseModel):
    appEngine: AppEngine | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    cloudFunction: CloudFunctionModel | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    cloudRun: CloudRunModel | None = None
    """
    This field is only used for SERVERLESS NEGs.
    Only one of cloud_run, app_engine, cloud_function or serverless_deployment may be set.
    Structure is documented below.
    """
    description: str | None = None
    """
    An optional description of this resource. Provide this property when
    you create the resource.
    """
    id: str | None = None
    """
    an identifier for the resource with format projects/{{project}}/regions/{{region}}/networkEndpointGroups/{{name}}
    """
    network: str | None = None
    """
    This field is only used for PSC and INTERNET NEGs.
    The URL of the network to which all network endpoints in the NEG belong. Uses
    "default" project network if unspecified.
    """
    networkEndpointType: str | None = None
    """
    Type of network endpoints in this network endpoint group. Defaults to SERVERLESS.
    Default value is SERVERLESS.
    Possible values are: SERVERLESS, PRIVATE_SERVICE_CONNECT, INTERNET_IP_PORT, INTERNET_FQDN_PORT, GCE_VM_IP_PORTMAP.
    """
    project: str | None = None
    """
    The ID of the project in which the resource belongs.
    If it is not provided, the provider project is used.
    """
    pscData: PscData | None = None
    """
    This field is only used for PSC NEGs.
    Structure is documented below.
    """
    pscTargetService: str | None = None
    """
    This field is only used for PSC and INTERNET NEGs.
    The target service url used to set up private service connection to
    a Google API or a PSC Producer Service Attachment.
    """
    region: str | None = None
    """
    A reference to the region where the regional NEGs reside.
    """
    selfLink: str | None = None
    """
    The URI of the created resource.
    """
    subnetwork: str | None = None
    """
    This field is only used for PSC NEGs.
    Optional URL of the subnetwork to which all network endpoints in the NEG belong.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class RegionNetworkEndpointGroup(BaseModel):
    apiVersion: Literal['compute.gcp.upbound.io/v1beta2'] | None = (
        'compute.gcp.upbound.io/v1beta2'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['RegionNetworkEndpointGroup'] | None = 'RegionNetworkEndpointGroup'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    RegionNetworkEndpointGroupSpec defines the desired state of RegionNetworkEndpointGroup
    """
    status: Status | None = None
    """
    RegionNetworkEndpointGroupStatus defines the observed state of RegionNetworkEndpointGroup.
    """


class RegionNetworkEndpointGroupList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[RegionNetworkEndpointGroup]
    """
    List of regionnetworkendpointgroups. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """