# generated by datamodel-codegen:
#   filename:  workdir/compute_gcp_upbound_io_v1beta1_routerinterface.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class RouterRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class RouterSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class VpnTunnelRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class VpnTunnelSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    interconnectAttachment: str | None = None
    """
    The name or resource link to the
    VLAN interconnect for this interface. Changing this forces a new interface to
    be created. Only one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """
    ipRange: str | None = None
    """
    IP address and range of the interface. The IP range must be
    in the RFC3927 link-local IP space. Changing this forces a new interface to be created.
    """
    ipVersion: str | None = None
    """
    IP version of this interface. Can be either IPV4 or IPV6.
    """
    name: str | None = None
    """
    A unique name for the interface, required by GCE. Changing
    this forces a new interface to be created.
    """
    privateIpAddress: str | None = None
    """
    The regional private internal IP address that is used
    to establish BGP sessions to a VM instance acting as a third-party Router Appliance. Changing this forces a new interface to be created.
    """
    project: str | None = None
    """
    The ID of the project in which this interface's router belongs.
    If it is not provided, the provider project is used. Changing this forces a new interface to be created.
    """
    redundantInterface: str | None = None
    """
    The name of the interface that is redundant to
    this interface. Changing this forces a new interface to be created.
    """
    region: str | None = None
    """
    The region this interface's router sits in.
    If not specified, the project region will be used. Changing this forces a new interface to be created.
    """
    router: str | None = None
    """
    The name of the router this interface will be attached to.
    Changing this forces a new interface to be created.
    """
    routerRef: RouterRef | None = None
    """
    Reference to a Router in compute to populate router.
    """
    routerSelector: RouterSelector | None = None
    """
    Selector for a Router in compute to populate router.
    """
    subnetwork: str | None = None
    """
    The URI of the subnetwork resource that this interface
    belongs to, which must be in the same region as the Cloud Router. When you establish a BGP session to a VM instance using this interface, the VM instance must belong to the same subnetwork as the subnetwork specified here. Changing this forces a new interface to be created. Only one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """
    vpnTunnel: str | None = None
    """
    The name or resource link to the VPN tunnel this
    interface will be linked to. Changing this forces a new interface to be created. Only
    one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """
    vpnTunnelRef: VpnTunnelRef | None = None
    """
    Reference to a VPNTunnel in compute to populate vpnTunnel.
    """
    vpnTunnelSelector: VpnTunnelSelector | None = None
    """
    Selector for a VPNTunnel in compute to populate vpnTunnel.
    """


class InitProvider(BaseModel):
    interconnectAttachment: str | None = None
    """
    The name or resource link to the
    VLAN interconnect for this interface. Changing this forces a new interface to
    be created. Only one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """
    ipRange: str | None = None
    """
    IP address and range of the interface. The IP range must be
    in the RFC3927 link-local IP space. Changing this forces a new interface to be created.
    """
    ipVersion: str | None = None
    """
    IP version of this interface. Can be either IPV4 or IPV6.
    """
    name: str | None = None
    """
    A unique name for the interface, required by GCE. Changing
    this forces a new interface to be created.
    """
    privateIpAddress: str | None = None
    """
    The regional private internal IP address that is used
    to establish BGP sessions to a VM instance acting as a third-party Router Appliance. Changing this forces a new interface to be created.
    """
    project: str | None = None
    """
    The ID of the project in which this interface's router belongs.
    If it is not provided, the provider project is used. Changing this forces a new interface to be created.
    """
    redundantInterface: str | None = None
    """
    The name of the interface that is redundant to
    this interface. Changing this forces a new interface to be created.
    """
    region: str | None = None
    """
    The region this interface's router sits in.
    If not specified, the project region will be used. Changing this forces a new interface to be created.
    """
    router: str | None = None
    """
    The name of the router this interface will be attached to.
    Changing this forces a new interface to be created.
    """
    routerRef: RouterRef | None = None
    """
    Reference to a Router in compute to populate router.
    """
    routerSelector: RouterSelector | None = None
    """
    Selector for a Router in compute to populate router.
    """
    subnetwork: str | None = None
    """
    The URI of the subnetwork resource that this interface
    belongs to, which must be in the same region as the Cloud Router. When you establish a BGP session to a VM instance using this interface, the VM instance must belong to the same subnetwork as the subnetwork specified here. Changing this forces a new interface to be created. Only one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """
    vpnTunnel: str | None = None
    """
    The name or resource link to the VPN tunnel this
    interface will be linked to. Changing this forces a new interface to be created. Only
    one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """
    vpnTunnelRef: VpnTunnelRef | None = None
    """
    Reference to a VPNTunnel in compute to populate vpnTunnel.
    """
    vpnTunnelSelector: VpnTunnelSelector | None = None
    """
    Selector for a VPNTunnel in compute to populate vpnTunnel.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class AtProvider(BaseModel):
    id: str | None = None
    """
    an identifier for the resource with format {{region}}/{{router}}/{{name}}
    """
    interconnectAttachment: str | None = None
    """
    The name or resource link to the
    VLAN interconnect for this interface. Changing this forces a new interface to
    be created. Only one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """
    ipRange: str | None = None
    """
    IP address and range of the interface. The IP range must be
    in the RFC3927 link-local IP space. Changing this forces a new interface to be created.
    """
    ipVersion: str | None = None
    """
    IP version of this interface. Can be either IPV4 or IPV6.
    """
    name: str | None = None
    """
    A unique name for the interface, required by GCE. Changing
    this forces a new interface to be created.
    """
    privateIpAddress: str | None = None
    """
    The regional private internal IP address that is used
    to establish BGP sessions to a VM instance acting as a third-party Router Appliance. Changing this forces a new interface to be created.
    """
    project: str | None = None
    """
    The ID of the project in which this interface's router belongs.
    If it is not provided, the provider project is used. Changing this forces a new interface to be created.
    """
    redundantInterface: str | None = None
    """
    The name of the interface that is redundant to
    this interface. Changing this forces a new interface to be created.
    """
    region: str | None = None
    """
    The region this interface's router sits in.
    If not specified, the project region will be used. Changing this forces a new interface to be created.
    """
    router: str | None = None
    """
    The name of the router this interface will be attached to.
    Changing this forces a new interface to be created.
    """
    subnetwork: str | None = None
    """
    The URI of the subnetwork resource that this interface
    belongs to, which must be in the same region as the Cloud Router. When you establish a BGP session to a VM instance using this interface, the VM instance must belong to the same subnetwork as the subnetwork specified here. Changing this forces a new interface to be created. Only one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """
    vpnTunnel: str | None = None
    """
    The name or resource link to the VPN tunnel this
    interface will be linked to. Changing this forces a new interface to be created. Only
    one of vpn_tunnel, interconnect_attachment or subnetwork can be specified.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class Status(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class RouterInterface(BaseModel):
    apiVersion: Literal['compute.gcp.upbound.io/v1beta1'] | None = (
        'compute.gcp.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['RouterInterface'] | None = 'RouterInterface'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    RouterInterfaceSpec defines the desired state of RouterInterface
    """
    status: Status | None = None
    """
    RouterInterfaceStatus defines the observed state of RouterInterface.
    """


class RouterInterfaceList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[RouterInterface]
    """
    List of routerinterfaces. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """