apiVersion: infrastructure.modelplane.ai/v1alpha1
kind: ServingStack
metadata:
  name: west-gke-stack
  namespace: platform
spec:
  secrets:
    - type: Kubeconfig
      name: west-gke-kubeconfig
      key: kubeconfig
    - type: GCPServiceAccountKey
      name: west-gke-sa-key
      key: private_key
  versions:
    gatewayApi: "v1.5.1"
    certManager: "v1.17.1"
    envoyGateway: "v1.8.1"
  gateway:
    listeners:
      - name: http
        port: 80
        protocol: HTTP
