# generated by datamodel-codegen:
#   filename:  workdir/ops_crossplane_io_v1alpha1_cronoperation.yaml

from __future__ import annotations

from datetime import datetime
from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field

from ....k8s.apimachinery.pkg.apis.meta import v1


class SecretRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Credential(BaseModel):
    name: str
    """
    Name of this set of credentials.
    """
    secretRef: Optional[SecretRef] = None
    """
    A SecretRef is a reference to a secret containing credentials that should
    be supplied to the function.
    """
    source: Literal['None', 'Secret']
    """
    Source of the function credentials.
    """


class FunctionRef(BaseModel):
    name: str
    """
    Name of the referenced function.
    """


class RequiredResource(BaseModel):
    apiVersion: str
    """
    APIVersion of resources to select.
    """
    kind: str
    """
    Kind of resources to select.
    """
    matchLabels: Optional[Dict[str, str]] = None
    """
    MatchLabels matches resources by label selector. Only one of Name or
    MatchLabels may be specified.
    """
    name: Optional[str] = None
    """
    Name matches a single resource by name. Only one of Name or
    MatchLabels may be specified.
    """
    namespace: Optional[str] = None
    """
    Namespace to search for resources. Optional for cluster-scoped resources.
    """
    requirementName: str
    """
    RequirementName uniquely identifies this group of resources.
    This name will be used as the key in RunFunctionRequest.required_resources.
    """


class RequiredSchema(BaseModel):
    apiVersion: str
    """
    APIVersion of the resource kind whose schema is required, e.g. "example.org/v1".
    """
    kind: str
    """
    Kind of resource whose schema is required, e.g. "MyResource".
    """
    requirementName: str
    """
    RequirementName uniquely identifies this schema.
    This name will be used as the key in RunFunctionRequest.required_schemas.
    """


class Requirements(BaseModel):
    requiredResources: Optional[List[RequiredResource]] = None
    """
    RequiredResources that will be fetched before this pipeline step
    is called for the first time.
    """
    requiredSchemas: Optional[List[RequiredSchema]] = None
    """
    RequiredSchemas that will be fetched before this pipeline step
    is called for the first time.
    """


class PipelineItem(BaseModel):
    credentials: Optional[List[Credential]] = None
    """
    Credentials are optional credentials that the operation function needs.
    """
    functionRef: FunctionRef
    """
    FunctionRef is a reference to the function this step should
    execute.
    """
    input: Optional[Dict[str, Any]] = None
    """
    Input is an optional, arbitrary Kubernetes resource (i.e. a resource
    with an apiVersion and kind) that will be passed to the unction as
    the 'input' of its RunFunctionRequest.
    """
    requirements: Optional[Requirements] = None
    """
    Requirements are resource requirements that will be satisfied before
    this pipeline step is called for the first time. This allows
    pre-populating required resources without requiring a function to
    request them first.
    """
    step: str
    """
    Step name. Must be unique within its Pipeline.
    """


class Spec(BaseModel):
    mode: Literal['Pipeline'] = 'Pipeline'
    """
    Mode controls what type or "mode" of operation will be used.

    "Pipeline" indicates that an Operation specifies a pipeline of
    functions, each of which is responsible for implementing its logic.
    """
    pipeline: List[PipelineItem] = Field(..., max_length=99, min_length=1)
    """
    Pipeline is a list of operation function steps that will be used when
    this operation runs.
    """
    retryLimit: Optional[int] = None
    """
    RetryLimit configures how many times the operation may fail. When the
    failure limit is exceeded, the operation will not be retried.
    """


class OperationTemplate(BaseModel):
    metadata: Optional[Dict[str, Any]] = None
    """
    Standard object metadata.
    """
    spec: Spec
    """
    Spec is the specification of the Operation to be created.
    """


class SpecModel(BaseModel):
    concurrencyPolicy: Optional[Literal['Allow', 'Forbid', 'Replace']] = 'Allow'
    """
    ConcurrencyPolicy specifies how to treat concurrent executions of an
    operation.
    """
    failedHistoryLimit: Optional[int] = 1
    """
    FailedHistoryLimit is the number of failed Operations to retain.
    """
    operationTemplate: OperationTemplate
    """
    OperationTemplate is the template for the Operation to be created.
    """
    schedule: str
    """
    Schedule is the cron schedule for the operation.
    """
    startingDeadlineSeconds: Optional[int] = None
    """
    StartingDeadlineSeconds is the deadline in seconds for starting the
    operation if it misses its scheduled time for any reason.
    """
    successfulHistoryLimit: Optional[int] = 3
    """
    SuccessfulHistoryLimit is the number of successful Operations to retain.
    """


class Condition(BaseModel):
    lastTransitionTime: datetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: Optional[str] = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: Optional[int] = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class RunningOperationRef(BaseModel):
    name: str
    """
    Name of the active operation.
    """


class Status(BaseModel):
    conditions: Optional[List[Condition]] = None
    """
    Conditions of the resource.
    """
    lastScheduleTime: Optional[datetime] = None
    """
    LastScheduleTime is the last time the CronOperation was scheduled.
    """
    lastSuccessfulTime: Optional[datetime] = None
    """
    LastSuccessfulTime is the last time the CronOperation was successfully
    completed.
    """
    runningOperationRefs: Optional[List[RunningOperationRef]] = None
    """
    RunningOperationRefs is a list of currently running Operations.
    """


class CronOperation(BaseModel):
    apiVersion: Optional[Literal['ops.crossplane.io/v1alpha1']] = (
        'ops.crossplane.io/v1alpha1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Optional[Literal['CronOperation']] = 'CronOperation'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ObjectMeta] = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Optional[SpecModel] = None
    """
    CronOperationSpec specifies the desired state of a CronOperation.
    """
    status: Optional[Status] = None
    """
    CronOperationStatus represents the observed state of a CronOperation.
    """


class CronOperationList(BaseModel):
    apiVersion: Optional[str] = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: List[CronOperation]
    """
    List of cronoperations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: Optional[str] = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: Optional[v1.ListMeta] = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """