StylesPath = styles
MinAlertLevel = suggestion
Packages = Google, Microsoft, write-good, alex, proselint
Vocab = Modelplane

[*.md]
BasedOnStyles = Google, Microsoft, write-good, Modelplane, Vale, alex, proselint

Vale.Spelling = NO
write-good.Passive = suggestion
Microsoft.AMPM = NO
Microsoft.Auto = NO
Microsoft.Headings = NO
Microsoft.HeadingPunctuation = NO
Microsoft.Gender = NO
Microsoft.GenderBias = NO
Microsoft.Ellipses = NO
Microsoft.DateFormat = NO
Microsoft.Dashes = NO
Microsoft.Spacing = NO
Microsoft.Acronyms = NO
Microsoft.Semicolon = NO
Microsoft.OxfordComma = NO
Microsoft.Hyphens = NO

Google.Latin = NO
Google.Contractions = NO

# Disabled for content reasons.
Google.Will = NO
Google.OxfordComma = NO
Microsoft.We = NO
Microsoft.FirstPerson = NO
Microsoft.Quotes = NO
Microsoft.GeneralURL = NO
Microsoft.Adverbs = NO
Microsoft.Contractions = NO
Microsoft.Passive = NO
Microsoft.SentenceLength = NO
write-good.E-Prime = NO
Google.Parens = NO
Google.Semicolons = NO
Google.Passive = NO
Microsoft.Vocab = NO
alex.Ablist = NO
alex.LGBTQ = NO
alex.OCD = NO
alex.Press = NO
alex.ProfanityLikely = NO
alex.ProfanityMaybe = NO
alex.ProfanityUnlikely = NO
alex.Suicide = NO

TokenIgnores = (\(#.*\)),(\]\(),(http.*),(\!\[),(\d.*px),(\d\.\d\.\d),(\{\{<[^>]+>\}\})
BlockIgnores = (\{\{<\s*\/?.*>\}\}),(\{\{\<\/\*.*\*\/\>\}\})
