name: Docs

on:
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  prose:
    name: Prose
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Vale
        run: nix run .#docs-vale --print-build-logs -- --minAlertLevel=warning

  links:
    name: Links
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Check links
        run: nix run .#docs-htmltest --print-build-logs
